"""Entertainment, media, and gaming responses"""

ENTERTAINMENT = {
    # Entertainment
    "music": ["Music is wonderful! What kind do you like?", "I love talking about music!", "Music moves the soul! What's your favorite genre?", "Are you into rock, pop, classical, or something else?"],
    "movie": ["Movies are great! What's your favorite genre?", "I enjoy discussing films!", "Cinema is magical! Seen anything good lately?", "What kind of movies do you enjoy?"],
    "movies": ["Movies are fantastic! What genre do you prefer?", "I love film discussions!", "Any recent movies you'd recommend?"],
    "film": ["Films are a great art form!", "Cinema is wonderful! What do you enjoy watching?", "Movies can be so moving!"],
    "song": ["Songs can be so powerful! What's your favorite?", "Music touches the heart!", "Do you have a favorite artist?"],
    "show": ["TV shows are great! What are you watching?", "Any shows you'd recommend?", "Binge-watching anything good?"],
    "series": ["Series are so addictive! What do you watch?", "Any good series recommendations?", "I love a good storyline!"],
    "netflix": ["Streaming is so convenient! What do you watch?", "Any Netflix recommendations?", "So much content to explore!"],
    "youtube": ["YouTube has everything! What do you watch there?", "So many creators to follow!", "What channels do you like?"],
    "game": ["Gaming is fun! What games do you play?", "Video games or board games?", "Gaming is such a great hobby!"],
    "games": ["Games are awesome! What do you play?", "Are you a casual or hardcore gamer?", "What platform do you game on?"],
    "gaming": ["Gaming is a great pastime!", "What's your favorite game genre?", "PC or console gaming?"],
    "video": ["Videos are entertaining!", "What kind of videos do you enjoy?", "Visual content is so engaging!"],
    "anime": ["Anime is amazing! What's your favorite?", "So many great anime series!", "Are you into shonen, seinen, or slice of life?"],
    "manga": ["Manga is wonderful! What do you read?", "Japanese comics are so creative!", "Any manga recommendations?"],
    "comic": ["Comics are great! Marvel or DC?", "Graphic novels are an art form!", "Who's your favorite superhero?"],
    "book": ["Reading is wonderful! What genres do you enjoy?", "Books are great! Any favorites?", "A good book is priceless!"],
    "books": ["Books open new worlds! What do you read?", "Reading is such a great habit!", "Fiction or non-fiction?"],
    "reading": ["Reading expands the mind!", "What are you reading currently?", "Books are magical!"],
    "podcast": ["Podcasts are great for learning!", "What podcasts do you listen to?", "Audio content is so convenient!"],
    
    # Social Media & Internet Culture
    "tiktok": ["TikTok is so addictive!", "Short videos are fun!", "What's trending?"],
    "instagram": ["Instagram is visual!", "Photos and reels!", "Social sharing!"],
    "twitter": ["Twitter is fast-paced!", "Tweets and trends!", "What's happening?"],
    "facebook": ["Facebook connects people!", "Social networking!", "Staying in touch!"],
    "reddit": ["Reddit has everything!", "Subreddits galore!", "The front page of the internet!"],
    "snapchat": ["Snapchat is fun!", "Disappearing messages!", "Filters!"],
    "twitch": ["Twitch is for gamers!", "Live streaming!", "Chat and watch!"],
    "discord": ["Discord is great for communities!", "Voice and text chat!", "Gaming servers!"],
    "meme": ["Memes are hilarious!", "Internet humor!", "Relatable content!"],
    "memes": ["Memes make life better!", "Internet culture!", "So funny!"],
    "viral": ["Going viral is crazy!", "Internet fame!", "Spreading fast!"],
    "trending": ["What's trending?", "Hot topics!", "Popular now!"],
    "influencer": ["Influencers shape opinions!", "Content creators!", "Social media stars!"],
    "follower": ["Followers show support!", "Social media metrics!", "Community!"],
    "like": ["Likes feel good!", "Appreciation!", "Engagement!"],
    "share": ["Sharing spreads ideas!", "Social connection!", "Community!"],
    "post": ["Posts express thoughts!", "Content creation!", "Sharing!"],
    "comment": ["Comments create conversation!", "Feedback!", "Engagement!"],
    "subscribe": ["Subscribing shows support!", "Following content!", "Stay updated!"],
    "stream": ["Streaming is live entertainment!", "Real-time content!", "Interactive!"],
    "vlog": ["Vlogs are personal!", "Video diaries!", "Life sharing!"],
    "blog": ["Blogs share knowledge!", "Written content!", "Personal expression!"],
    "selfie": ["Selfies capture moments!", "Self-portraits!", "Memories!"],
    "hashtag": ["Hashtags organize content!", "Trending topics!", "Discovery!"],
    "emoji": ["Emojis express emotions!", "Digital expressions!", "Fun symbols!"],
    
    # Music - More Genres & Artists
    "rock": ["Rock music is powerful!", "Guitar riffs!", "Classic genre!"],
    "pop": ["Pop is catchy!", "Chart toppers!", "Mainstream hits!"],
    "hiphop": ["Hip hop is culture!", "Beats and rhymes!", "Urban music!"],
    "rap": ["Rap is lyrical!", "Flow and bars!", "Wordplay!"],
    "jazz": ["Jazz is sophisticated!", "Improvisation!", "Smooth sounds!"],
    "classical": ["Classical is timeless!", "Orchestral beauty!", "Composers!"],
    "country": ["Country tells stories!", "Guitars and twang!", "Nashville vibes!"],
    "electronic": ["Electronic is modern!", "Beats and drops!", "Dance music!"],
    "edm": ["EDM gets you moving!", "Festival vibes!", "Drop the bass!"],
    "metal": ["Metal is intense!", "Heavy riffs!", "Headbanging!"],
    "blues": ["Blues has soul!", "Emotional music!", "Guitar licks!"],
    "reggae": ["Reggae is chill!", "Island vibes!", "One love!"],
    "indie": ["Indie is unique!", "Alternative sounds!", "Underground!"],
    "rnb": ["R&B is smooth!", "Soul music!", "Rhythm and blues!"],
    "kpop": ["K-pop is global!", "Korean pop!", "Dance and visuals!"],
    "latin": ["Latin music is vibrant!", "Rhythm!", "Fiesta!"],
    "acoustic": ["Acoustic is pure!", "Unplugged!", "Raw sound!"],
    "playlist": ["Playlists set the mood!", "Curated music!", "Shuffle play!"],
    "concert": ["Concerts are electric!", "Live music!", "Amazing energy!"],
    "festival": ["Festivals are experiences!", "Music and vibes!", "Summer fun!"],
    "album": ["Albums tell stories!", "Full collections!", "Artist vision!"],
    "spotify": ["Spotify has everything!", "Streaming music!", "Discover new artists!"],
    "lyrics": ["Lyrics tell stories!", "Words matter!", "Sing along!"],
    "guitar": ["Guitars are iconic!", "String instruments!", "Rock on!"],
    "piano": ["Piano is elegant!", "Keys and melodies!", "Beautiful instrument!"],
    "drums": ["Drums set the beat!", "Rhythm section!", "Bang bang!"],
    "singer": ["Singers have talent!", "Vocal power!", "Voice!"],
    "band": ["Bands make music together!", "Group harmony!", "Collaboration!"],
    "dj": ["DJs mix tracks!", "Party starters!", "Beat masters!"],
    
    # Movies & TV - More Specific
    "horror": ["Horror is thrilling!", "Scary movies!", "Adrenaline rush!"],
    "comedy": ["Comedy makes us laugh!", "Humor!", "Feel-good!"],
    "drama": ["Drama is emotional!", "Compelling stories!", "Character depth!"],
    "action": ["Action is exciting!", "Explosions!", "Adrenaline!"],
    "romance": ["Romance is sweet!", "Love stories!", "Feel the feels!"],
    "thriller": ["Thrillers are tense!", "Suspense!", "Edge of your seat!"],
    "scifi": ["Sci-fi imagines futures!", "Science fiction!", "Space and tech!"],
    "fantasy": ["Fantasy is magical!", "Other worlds!", "Dragons and wizards!"],
    "documentary": ["Documentaries inform!", "Real stories!", "Learning!"],
    "animation": ["Animation is creative!", "Cartoons!", "Visual art!"],
    "superhero": ["Superhero movies are epic!", "Powers!", "Saving the world!"],
    "marvel": ["Marvel is massive!", "MCU!", "Avengers assemble!"],
    "dc": ["DC has legends!", "Batman, Superman!", "Justice League!"],
    "disney": ["Disney is magical!", "Classic stories!", "Family entertainment!"],
    "pixar": ["Pixar touches hearts!", "Animation genius!", "Emotional stories!"],
    "streaming": ["Streaming changed everything!", "On-demand!", "Binge-watching!"],
    "hbo": ["HBO has quality!", "Premium content!", "Must-watch shows!"],
    "hulu": ["Hulu has variety!", "Streaming options!", "Great shows!"],
    "prime": ["Prime Video is packed!", "Amazon content!", "So much to watch!"],
    "actor": ["Actors bring stories to life!", "Performance!", "Talent!"],
    "actress": ["Actresses are talented!", "Performance art!", "Screen presence!"],
    "director": ["Directors create vision!", "Behind the camera!", "Filmmaking!"],
    "oscar": ["Oscars celebrate film!", "Awards!", "Hollywood's best!"],
    "cinema": ["Cinema is an experience!", "Big screen!", "Movie magic!"],
    "popcorn": ["Popcorn and movies!", "Classic combo!", "Snack time!"],
    "trailer": ["Trailers build hype!", "Coming soon!", "Sneak peek!"],
    "sequel": ["Sequels continue stories!", "Part two!", "More adventures!"],
    "remake": ["Remakes revisit classics!", "New versions!", "Fresh takes!"],
    "episode": ["Episodes keep us hooked!", "TV series!", "Next one please!"],
    "season": ["Seasons bring more!", "TV series!", "Binge-worthy!"],
    "finale": ["Finales are intense!", "Endings!", "Conclusions!"],
    "cliffhanger": ["Cliffhangers are cruel!", "Suspense!", "Need to know!"],
    
    # Gaming - More Specific
    "playstation": ["PlayStation is awesome!", "Sony gaming!", "PS5!"],
    "xbox": ["Xbox is great!", "Microsoft gaming!", "Game Pass!"],
    "nintendo": ["Nintendo is iconic!", "Mario and Zelda!", "Switch!"],
    "pc": ["PC gaming is powerful!", "Master race!", "Customization!"],
    "console": ["Consoles are convenient!", "Gaming systems!", "Plug and play!"],
    "controller": ["Controllers feel good!", "Gaming input!", "Button mashing!"],
    "keyboard": ["Keyboards for gaming!", "Mechanical!", "RGB lights!"],
    "mouse": ["Gaming mice are precise!", "Accuracy!", "Click click!"],
    "headset": ["Headsets immerse you!", "Audio!", "Game sounds!"],
    "fps": ["FPS games are intense!", "First-person shooters!", "Aim and fire!"],
    "rpg": ["RPGs are immersive!", "Role-playing!", "Level up!"],
    "mmo": ["MMOs are massive!", "Online worlds!", "Multiplayer!"],
    "moba": ["MOBAs are competitive!", "Team battles!", "Strategy!"],
    "battle": ["Battle games are exciting!", "Combat!", "Victory!"],
    "fortnite": ["Fortnite is popular!", "Battle royale!", "Victory royale!"],
    "minecraft": ["Minecraft is creative!", "Building blocks!", "Endless possibilities!"],
    "zelda": ["Zelda is legendary!", "Nintendo classic!", "Link's adventures!"],
    "mario": ["Mario is iconic!", "Nintendo mascot!", "It's-a me!"],
    "pokemon": ["Pokemon is beloved!", "Gotta catch 'em all!", "Creatures!"],
    "cod": ["Call of Duty is intense!", "Shooter!", "Multiplayer battles!"],
    "gta": ["GTA is wild!", "Open world!", "Chaos and fun!"],
    "esports": ["Esports is competitive!", "Pro gaming!", "Tournaments!"],
    "streamer": ["Streamers entertain!", "Content creators!", "Live gameplay!"],
    "multiplayer": ["Multiplayer is social!", "Play together!", "Team up!"],
    "singleplayer": ["Single-player is immersive!", "Story focus!", "Solo adventure!"],
    "level": ["Leveling up!", "Progress!", "Getting stronger!"],
    "boss": ["Boss fights are epic!", "Big enemies!", "Challenge!"],
    "quest": ["Quests give purpose!", "Missions!", "Adventures!"],
    "loot": ["Loot is rewarding!", "Items!", "Treasure!"],
    "achievement": ["Achievements unlock!", "Accomplishments!", "Trophy!"],
    
    # Board Games & Card Games
    "chess": ["Chess is strategic!", "Ancient game!", "Checkmate!"],
    "checkers": ["Checkers is classic!", "Jump and capture!", "Simple fun!"],
    "backgammon": ["Backgammon uses dice!", "Ancient!", "Strategy and luck!"],
    "monopoly": ["Monopoly takes hours!", "Buy property!", "Classic!"],
    "scrabble": ["Scrabble uses words!", "Vocabulary!", "Triple word score!"],
    "risk": ["Risk is world conquest!", "Strategy!", "Armies!"],
    "clue": ["Clue solves mysteries!", "Whodunit!", "Detective!"],
    "battleship": ["Battleship is naval warfare!", "You sunk my ship!", "Grid!"],
    "connect four": ["Connect Four is simple!", "Strategy!", "Four in a row!"],
    "jenga": ["Jenga is tense!", "Stacking!", "Don't let it fall!"],
    "uno": ["UNO is card chaos!", "Reverse!", "Draw four!"],
    "poker": ["Poker is betting!", "Bluffing!", "Card game!"],
    "blackjack": ["Blackjack is 21!", "Casino game!", "Hit or stand!"],
    "bridge": ["Bridge is complex!", "Partner card game!", "Bidding!"],
    "rummy": ["Rummy is matching!", "Card game!", "Sets and runs!"],
    "solitaire": ["Solitaire is solo!", "Card game!", "Patience!"],
    "hearts": ["Hearts avoids points!", "Card game!", "Shoot the moon!"],
    "spades": ["Spades is trick-taking!", "Partner game!", "Bidding!"],
    "catan": ["Catan trades resources!", "Modern classic!", "Settlers!"],
    "ticket to ride": ["Ticket to Ride builds trains!", "Routes!", "Strategy!"],
    "pandemic": ["Pandemic fights disease!", "Cooperative!", "Save the world!"],
    "carcassonne": ["Carcassonne places tiles!", "Medieval!", "Meeples!"],
    "codenames": ["Codenames is word association!", "Party game!", "Teams!"],
    "dixit": ["Dixit is storytelling!", "Art cards!", "Creative!"],
    "azul": ["Azul is tile drafting!", "Beautiful!", "Portuguese tiles!"],
    "splendor": ["Splendor collects gems!", "Engine building!", "Renaissance!"],
    "dominion": ["Dominion invented deck building!", "Cards!", "Strategy!"],
    "magic the gathering": ["Magic is collectible cards!", "Fantasy!", "Competitive!"],
    "dungeons and dragons": ["D&D is roleplaying!", "Fantasy!", "Imagination!"],
}
