"""Food, drink, and cuisine responses"""

FOOD = {
    # Food & Drink
    "food": ["Food is one of life's pleasures! What's your favorite?", "Yum! What kind of food do you enjoy?", "Cooking or eating out?"],
    "eating": ["Eating well is important!", "What's your favorite meal?", "Any favorite restaurants?"],
    "cooking": ["Cooking is an art! Do you cook?", "What's your signature dish?", "Homemade food is the best!"],
    "restaurant": ["Restaurants are fun! Any favorites?", "What cuisine do you prefer?", "Fine dining or casual?"],
    "pizza": ["Pizza is amazing! What toppings do you like?", "Pizza is life! Thin or thick crust?", "Who doesn't love pizza?"],
    "burger": ["Burgers are classic! How do you like yours?", "A good burger is hard to beat!", "Beef, chicken, or veggie?"],
    "coffee": ["Coffee is essential! How do you take yours?", "Caffeine keeps us going!", "Latte, espresso, or black?"],
    "tea": ["Tea is so calming! What's your favorite?", "Tea time is the best time!", "Green, black, or herbal?"],
    "beer": ["Beer has such variety! What's your favorite?", "Craft or classic?", "Cheers to that!"],
    "wine": ["Wine is sophisticated! Red or white?", "Wine pairs well with life!", "Any favorite vineyards?"],
    "chocolate": ["Chocolate is heavenly!", "Dark, milk, or white chocolate?", "Chocolate fixes everything!"],
    "breakfast": ["Breakfast is the most important meal!", "What's your go-to breakfast?", "Pancakes or eggs?"],
    "lunch": ["Lunch breaks are important!", "What do you usually have for lunch?", "Light or heavy lunch?"],
    "dinner": ["Dinner is quality time!", "What's for dinner tonight?", "Home-cooked or takeout?"],
    "snack": ["Snacks are the best!", "What's your favorite snack?", "Sweet or savory snacks?"],
    
    # Food - More Specific
    "sushi": ["Sushi is delicious!", "Japanese cuisine!", "Fresh and tasty!"],
    "pasta": ["Pasta is comforting!", "Italian classic!", "So many shapes!"],
    "rice": ["Rice is a staple!", "Versatile grain!", "Goes with everything!"],
    "chicken": ["Chicken is versatile!", "Protein!", "So many recipes!"],
    "beef": ["Beef is hearty!", "Meat lovers!", "Steak anyone?"],
    "pork": ["Pork is tasty!", "Bacon!", "Versatile meat!"],
    "fish": ["Fish is healthy!", "Omega-3s!", "Seafood lovers!"],
    "salad": ["Salads are healthy!", "Fresh veggies!", "Light and nutritious!"],
    "soup": ["Soup is comforting!", "Warm and cozy!", "Soul food!"],
    "sandwich": ["Sandwiches are convenient!", "Lunch staple!", "So many fillings!"],
    "taco": ["Tacos are amazing!", "Mexican cuisine!", "Taco Tuesday!"],
    "curry": ["Curry is flavorful!", "Spices galore!", "Indian cuisine!"],
    "noodles": ["Noodles are great!", "Asian cuisine!", "Slurp worthy!"],
    "steak": ["Steak is indulgent!", "Meat lovers' dream!", "How do you like yours?"],
    "bacon": ["Bacon is irresistible!", "Crispy goodness!", "Everything's better with bacon!"],
    "eggs": ["Eggs are versatile!", "Breakfast staple!", "Protein packed!"],
    "cheese": ["Cheese is wonderful!", "So many varieties!", "Cheesy goodness!"],
    "bread": ["Bread is life!", "Fresh baked!", "Carb love!"],
    "cake": ["Cake is celebratory!", "Sweet treats!", "Dessert time!"],
    "cookie": ["Cookies are sweet!", "Baked goodness!", "Milk and cookies!"],
    "icecream": ["Ice cream is heavenly!", "Cold treats!", "So many flavors!"],
    "fruit": ["Fruit is healthy!", "Natural sweetness!", "Vitamins!"],
    "vegetable": ["Vegetables are nutritious!", "Eat your greens!", "Healthy choices!"],
    "vegan": ["Vegan is a lifestyle!", "Plant-based!", "Compassionate eating!"],
    "vegetarian": ["Vegetarian is healthy!", "No meat!", "Plant-forward!"],
    "organic": ["Organic is natural!", "Clean eating!", "Pesticide-free!"],
    "dessert": ["Desserts are the best part!", "Sweet endings!", "Treat yourself!"],
    "spicy": ["Spicy food is exciting!", "Heat lovers!", "Bring the fire!"],
    "sweet": ["Sweet treats!", "Sugar!", "Delicious!"],
    "sour": ["Sour is tangy!", "Citrus!", "Puckering!"],
    "bitter": ["Bitter has depth!", "Complex flavors!", "Acquired taste!"],
    "salty": ["Salty snacks!", "Savory!", "Crunchy!"],
    
    # World Cuisines
    "chinese": ["Chinese food is diverse!", "Dim sum!", "Flavors!"],
    "japanese": ["Japanese food is art!", "Sushi!", "Precision!"],
    "korean": ["Korean food is bold!", "BBQ!", "Kimchi!"],
    "thai": ["Thai food is balanced!", "Spicy and sweet!", "Flavors!"],
    "vietnamese": ["Vietnamese food is fresh!", "Pho!", "Herbs!"],
    "indian": ["Indian food is spiced!", "Curry!", "Diverse!"],
    "mexican": ["Mexican food is vibrant!", "Tacos!", "Spicy!"],
    "italian": ["Italian food is classic!", "Pasta!", "Pizza!"],
    "french": ["French food is refined!", "Cuisine!", "Techniques!"],
    "greek": ["Greek food is Mediterranean!", "Healthy!", "Olive oil!"],
    "spanish": ["Spanish food is tapas!", "Small plates!", "Paella!"],
    "mediterranean": ["Mediterranean diet is healthy!", "Fresh!", "Olive oil!"],
    "middleeastern": ["Middle Eastern food is flavorful!", "Hummus!", "Spices!"],
    "african": ["African food is diverse!", "Varied cuisines!", "Bold flavors!"],
    "caribbean": ["Caribbean food is tropical!", "Jerk seasoning!", "Island flavors!"],
    "brazilian": ["Brazilian food is hearty!", "Churrasco!", "BBQ!"],
    "peruvian": ["Peruvian food is unique!", "Ceviche!", "Diverse influences!"],
    "dim sum": ["Dim sum is sharing!", "Chinese brunch!", "Small dishes!"],
    "ramen": ["Ramen is comforting!", "Japanese noodles!", "Broth!"],
    "pho": ["Pho is aromatic!", "Vietnamese soup!", "Herbs!"],
    "bibimbap": ["Bibimbap is colorful!", "Korean rice bowl!", "Mix it up!"],
    "paella": ["Paella is festive!", "Spanish rice!", "Seafood!"],
    "hummus": ["Hummus is creamy!", "Chickpea dip!", "Healthy!"],
    "falafel": ["Falafel is crispy!", "Chickpea fritters!", "Middle Eastern!"],
    "gyro": ["Gyros are savory!", "Greek wrap!", "Meat!"],
    "croissant": ["Croissants are buttery!", "French pastry!", "Flaky!"],
    "crepe": ["Crepes are thin!", "French pancakes!", "Sweet or savory!"],
    "gelato": ["Gelato is creamy!", "Italian ice cream!", "Smooth!"],
    "tiramisu": ["Tiramisu is indulgent!", "Italian dessert!", "Coffee and mascarpone!"],
    "baklava": ["Baklava is sweet!", "Middle Eastern pastry!", "Honey and nuts!"],
    
    # More specific dishes
    "sashimi": ["Sashimi is raw fish!", "Japanese!", "Fresh!"],
    "tempura": ["Tempura is fried!", "Japanese!", "Crispy!"],
    "teriyaki": ["Teriyaki is sweet and savory!", "Japanese!", "Glazed!"],
    "kimchi": ["Kimchi is fermented!", "Korean!", "Spicy!"],
    "bulgogi": ["Bulgogi is marinated beef!", "Korean BBQ!", "Delicious!"],
    "padthai": ["Pad Thai is stir-fried noodles!", "Thai!", "Peanuts!"],
    "banh mi": ["Banh mi is Vietnamese sandwich!", "Fusion!", "Crispy bread!"],
    "samosa": ["Samosas are fried pastries!", "Indian!", "Savory!"],
    "naan": ["Naan is Indian bread!", "Fluffy!", "Delicious!"],
    "biryani": ["Biryani is spiced rice!", "Indian!", "Fragrant!"],
    "tikka": ["Tikka masala is creamy!", "Indian!", "Flavorful!"],
    "fajita": ["Fajitas are sizzling!", "Mexican!", "Grilled!"],
    "enchilada": ["Enchiladas are rolled!", "Mexican!", "Saucy!"],
    "quesadilla": ["Quesadillas are cheesy!", "Mexican!", "Crispy!"],
    "guacamole": ["Guacamole is avocado dip!", "Mexican!", "Fresh!"],
    "bruschetta": ["Bruschetta is Italian appetizer!", "Tomato!", "Garlic bread!"],
    "risotto": ["Risotto is creamy rice!", "Italian!", "Rich!"],
    "gnocchi": ["Gnocchi are potato dumplings!", "Italian!", "Pillowy!"],
    "lasagna": ["Lasagna is layered!", "Italian!", "Cheesy!"],
    "carbonara": ["Carbonara is creamy pasta!", "Italian!", "Bacon and egg!"],
    "tapas": ["Tapas are small plates!", "Spanish!", "Sharing!"],
    "gazpacho": ["Gazpacho is cold soup!", "Spanish!", "Refreshing!"],
    "baguette": ["Baguettes are crusty!", "French bread!", "Classic!"],
    "quiche": ["Quiche is egg pie!", "French!", "Savory!"],
    "souvlaki": ["Souvlaki is Greek skewers!", "Grilled meat!", "Delicious!"],
    "moussaka": ["Moussaka is Greek casserole!", "Eggplant!", "Layers!"],
    "shawarma": ["Shawarma is rotisserie meat!", "Middle Eastern!", "Wrapped!"],
    "pierogi": ["Pierogies are dumplings!", "Polish!", "Filled!"],
    "borscht": ["Borscht is beet soup!", "Eastern European!", "Red!"],
    "schnitzel": ["Schnitzel is breaded meat!", "German!", "Crispy!"],
    "bratwurst": ["Bratwurst is German sausage!", "Grilled!", "Beer pairing!"],
    "fondue": ["Fondue is melted cheese!", "Swiss!", "Dipping!"],
    "wonton": ["Wontons are dumplings!", "Chinese!", "Soup or fried!"],
    "dimsum": ["Dim sum is small dishes!", "Chinese!", "Brunch!"],
    "springroll": ["Spring rolls are crispy!", "Asian!", "Wrapped!"],
    "friedrice": ["Fried rice is versatile!", "Asian!", "Wok!"],
    "stirfry": ["Stir fry is quick cooking!", "Asian!", "Wok!"],
    "miso": ["Miso is fermented soybean!", "Japanese!", "Soup base!"],
    "tofu": ["Tofu is versatile!", "Soy protein!", "Plant-based!"],
    "edamame": ["Edamame are soybeans!", "Japanese!", "Snack!"],
    "wasabi": ["Wasabi is spicy!", "Japanese!", "Green paste!"],
    "sriracha": ["Sriracha is hot sauce!", "Thai-American!", "Spicy!"],
    
    # Desserts & Sweets
    "brownie": ["Brownies are chocolatey!", "Fudgy or cakey!", "Delicious!"],
    "cheesecake": ["Cheesecake is creamy!", "Rich!", "Many flavors!"],
    "pudding": ["Pudding is smooth!", "Creamy dessert!", "Comfort food!"],
    "mousse": ["Mousse is airy!", "Light and fluffy!", "Chocolate!"],
    "souffle": ["Souffles are delicate!", "Rise and fall!", "Impressive!"],
    "custard": ["Custard is eggy!", "Creamy!", "Classic!"],
    "flan": ["Flan has caramel!", "Spanish custard!", "Smooth!"],
    "creme brulee": ["Crème brûlée has torched sugar!", "Crack the top!", "French!"],
    "panna cotta": ["Panna cotta is Italian cream!", "Jiggly!", "Elegant!"],
    "macaron": ["Macarons are French cookies!", "Colorful!", "Delicate!"],
    "eclair": ["Eclairs are filled pastries!", "Chocolate topped!", "French!"],
    "profiterole": ["Profiteroles are cream puffs!", "Ice cream filled!", "Dessert!"],
    "cannoli": ["Cannoli are Italian tubes!", "Ricotta filled!", "Crispy!"],
    "biscotti": ["Biscotti are twice-baked!", "Italian cookies!", "Coffee dipping!"],
    "shortbread": ["Shortbread is buttery!", "Scottish!", "Crumbly!"],
    "scone": ["Scones are British!", "Tea time!", "Clotted cream!"],
    "muffin": ["Muffins are breakfast treats!", "Many flavors!", "Portable!"],
    "cupcake": ["Cupcakes are mini cakes!", "Frosted!", "Celebrations!"],
    "donut": ["Donuts are fried dough!", "Glazed or filled!", "Coffee pairing!"],
    "churro": ["Churros are fried dough!", "Cinnamon sugar!", "Spanish!"],
    "waffle": ["Waffles have pockets!", "Syrup catchers!", "Breakfast!"],
    "pancake": ["Pancakes are flat cakes!", "Stacks!", "Breakfast classic!"],
    "tart": ["Tarts have crusts!", "Fruit filled!", "Elegant!"],
    "pie": ["Pies are classic!", "Fruit or cream!", "American!"],
    "cobbler": ["Cobblers have biscuit tops!", "Fruit dessert!", "Southern!"],
    "crisp": ["Crisps have oat topping!", "Fruit dessert!", "Easy!"],
    "truffle": ["Truffles are chocolate balls!", "Rich!", "Indulgent!"],
    "praline": ["Pralines are nutty!", "Caramelized!", "Southern!"],
    "fudge": ["Fudge is dense chocolate!", "Sweet!", "Rich!"],
    "toffee": ["Toffee is buttery candy!", "Crunchy!", "English!"],
    "caramel": ["Caramel is melted sugar!", "Gooey!", "Sweet!"],
    "marshmallow": ["Marshmallows are fluffy!", "Soft!", "S'mores!"],
    "meringue": ["Meringue is whipped whites!", "Crispy or soft!", "Light!"],
    "sorbet": ["Sorbet is fruit ice!", "Dairy-free!", "Refreshing!"],
    "sherbet": ["Sherbet has some dairy!", "Fruity!", "Creamy!"],
    "frozen yogurt": ["Froyo is tangy!", "Healthier option!", "Toppings!"],
    "milkshake": ["Milkshakes are blended!", "Thick and creamy!", "Nostalgic!"],
    "sundae": ["Sundaes have toppings!", "Ice cream treat!", "Indulgent!"],
    "banana split": ["Banana splits are classic!", "Three scoops!", "Toppings galore!"],
    
    # Pasta Types
    "spaghetti": ["Spaghetti is long and thin!", "Classic!", "Twirl it!"],
    "linguine": ["Linguine is flat!", "Like spaghetti!", "Seafood pairing!"],
    "fettuccine": ["Fettuccine is wide and flat!", "Alfredo!", "Creamy sauces!"],
    "pappardelle": ["Pappardelle is extra wide!", "Hearty!", "Meat sauces!"],
    "tagliatelle": ["Tagliatelle is ribbon-like!", "Bologna!", "Ragu!"],
    "penne": ["Penne has ridges!", "Tube pasta!", "Holds sauce!"],
    "rigatoni": ["Rigatoni is large tubes!", "Chunky sauces!", "Baked dishes!"],
    "ziti": ["Ziti is smooth tubes!", "Baked ziti!", "Casseroles!"],
    "macaroni": ["Macaroni is elbow shaped!", "Mac and cheese!", "Classic!"],
    "fusilli": ["Fusilli is spiral!", "Twisted!", "Salads!"],
    "rotini": ["Rotini is corkscrew!", "Holds sauce!", "Colorful!"],
    "farfalle": ["Farfalle is bow-tie!", "Butterfly pasta!", "Pretty!"],
    "orecchiette": ["Orecchiette is ear-shaped!", "Puglia!", "Broccoli rabe!"],
    "conchiglie": ["Conchiglie is shell-shaped!", "Stuffable!", "Sauce catchers!"],
    "cavatappi": ["Cavatappi is corkscrew!", "Hollow!", "Fun shape!"],
    "orzo": ["Orzo is rice-shaped!", "Soups!", "Salads!"],
    "couscous": ["Couscous is tiny!", "North African!", "Quick cooking!"],
    "ravioli": ["Ravioli is stuffed!", "Pockets of filling!", "Classic!"],
    "tortellini": ["Tortellini is ring-shaped!", "Stuffed!", "Bologna!"],
    "agnolotti": ["Agnolotti is stuffed!", "Piedmont!", "Meat filled!"],
    "cannelloni": ["Cannelloni is stuffed tubes!", "Baked!", "Ricotta!"],
    "manicotti": ["Manicotti is large tubes!", "Stuffed!", "Cheese filled!"],
    "lasagne": ["Lasagne is layered sheets!", "Baked!", "Comfort food!"],
    "udon": ["Udon is thick Japanese!", "Chewy!", "Soup!"],
    "soba": ["Soba is buckwheat!", "Japanese!", "Cold or hot!"],
    "vermicelli": ["Vermicelli is very thin!", "Asian or Italian!", "Delicate!"],
    "angel hair": ["Angel hair is super thin!", "Capellini!", "Light sauces!"],
    "bucatini": ["Bucatini has a hole!", "Thick spaghetti!", "Amatriciana!"],
    
    # Bread Types
    "sourdough": ["Sourdough is tangy!", "Natural yeast!", "Artisan!"],
    "ciabatta": ["Ciabatta is Italian!", "Chewy!", "Sandwiches!"],
    "focaccia": ["Focaccia is flat Italian!", "Olive oil!", "Herbs!"],
    "brioche": ["Brioche is buttery!", "French!", "Rich!"],
    "challah": ["Challah is braided!", "Jewish!", "Eggy!"],
    "pita": ["Pita has a pocket!", "Middle Eastern!", "Stuffable!"],
    "roti": ["Roti is unleavened!", "Indian!", "Whole wheat!"],
    "tortilla": ["Tortillas are flatbreads!", "Mexican!", "Corn or flour!"],
    "pretzel": ["Pretzels are twisted!", "Salted!", "German origin!"],
    "bagel": ["Bagels are boiled then baked!", "New York!", "Chewy!"],
    "english muffin": ["English muffins have nooks!", "Toasted!", "Breakfast!"],
    "cornbread": ["Cornbread is Southern!", "Sweet or savory!", "Crumbly!"],
    "pumpernickel": ["Pumpernickel is dark rye!", "German!", "Dense!"],
    "rye": ["Rye bread is earthy!", "Caraway!", "Deli style!"],
    "multigrain": ["Multigrain has many grains!", "Healthy!", "Nutty!"],
    "whole wheat": ["Whole wheat is healthier!", "Fiber!", "Nutty flavor!"],
    "white bread": ["White bread is classic!", "Soft!", "Sandwiches!"],
    "french bread": ["French bread is crusty!", "Long loaves!", "Baguettes!"],
    "italian bread": ["Italian bread is chewy!", "Crusty!", "Olive oil!"],
    "banana bread": ["Banana bread is sweet!", "Ripe bananas!", "Moist!"],
    "zucchini bread": ["Zucchini bread is sneaky healthy!", "Moist!", "Sweet!"],
    "pumpkin bread": ["Pumpkin bread is fall flavor!", "Spiced!", "Seasonal!"],
    "garlic bread": ["Garlic bread is savory!", "Buttery!", "Pasta pairing!"],
    "flatbread": ["Flatbreads are versatile!", "Thin!", "Toppings!"],
    "crouton": ["Croutons are crunchy!", "Salad toppers!", "Seasoned!"],
    "breadstick": ["Breadsticks are crunchy!", "Dipping!", "Italian restaurants!"],
    "roll": ["Rolls are individual portions!", "Dinner rolls!", "Buttery!"],
    "biscuit": ["Biscuits are flaky!", "Southern!", "Butter and jam!"],
    
    # Cheese Types
    "cheddar": ["Cheddar is sharp!", "English origin!", "Versatile!"],
    "mozzarella": ["Mozzarella is stretchy!", "Pizza cheese!", "Italian!"],
    "parmesan": ["Parmesan is aged!", "Grated!", "Umami!"],
    "brie": ["Brie is soft and creamy!", "French!", "Rind is edible!"],
    "camembert": ["Camembert is soft!", "French!", "Similar to brie!"],
    "gouda": ["Gouda is Dutch!", "Mild to aged!", "Caramel notes!"],
    "gruyere": ["Gruyère is Swiss!", "Nutty!", "Fondue!"],
    "swiss": ["Swiss has holes!", "Mild!", "Sandwiches!"],
    "provolone": ["Provolone is Italian!", "Mild or sharp!", "Deli!"],
    "feta": ["Feta is crumbly!", "Greek!", "Tangy!"],
    "goat cheese": ["Goat cheese is tangy!", "Creamy!", "Salads!"],
    "ricotta": ["Ricotta is fresh!", "Creamy!", "Lasagna!"],
    "mascarpone": ["Mascarpone is rich!", "Italian!", "Tiramisu!"],
    "cream cheese": ["Cream cheese is spreadable!", "Bagels!", "Cheesecake!"],
    "cottage cheese": ["Cottage cheese is curds!", "Protein!", "Healthy!"],
    "blue cheese": ["Blue cheese is pungent!", "Veined!", "Strong!"],
    "gorgonzola": ["Gorgonzola is Italian blue!", "Creamy!", "Bold!"],
    "roquefort": ["Roquefort is French blue!", "Sheep's milk!", "Strong!"],
    "stilton": ["Stilton is English blue!", "Crumbly!", "Port pairing!"],
    "manchego": ["Manchego is Spanish!", "Sheep's milk!", "Nutty!"],
    "pecorino": ["Pecorino is Italian sheep!", "Sharp!", "Romano!"],
    "asiago": ["Asiago is Italian!", "Aged!", "Grating!"],
    "fontina": ["Fontina is Italian!", "Melty!", "Fondue!"],
    "havarti": ["Havarti is Danish!", "Creamy!", "Mild!"],
    "muenster": ["Muenster is mild!", "Orange rind!", "Melty!"],
    "colby": ["Colby is American!", "Mild!", "Similar to cheddar!"],
    "monterey jack": ["Monterey Jack is mild!", "California!", "Melty!"],
    "pepper jack": ["Pepper Jack is spicy!", "Jalapeño!", "Kick!"],
    "queso fresco": ["Queso fresco is Mexican!", "Fresh!", "Crumbly!"],
    "cotija": ["Cotija is Mexican!", "Aged!", "Crumbly!"],
    "paneer": ["Paneer is Indian!", "Fresh!", "Doesn't melt!"],
    "halloumi": ["Halloumi is grillable!", "Cypriot!", "Squeaky!"],
    "burrata": ["Burrata is creamy center!", "Fresh mozzarella!", "Luxurious!"],
    
    # Beverages
    "juice": ["Juice is refreshing!", "Fruit drinks!", "Vitamin C!"],
    "soda": ["Soda is fizzy!", "Soft drinks!", "Bubbles!"],
    "water": ["Water is essential!", "Hydration!", "Stay healthy!"],
    "smoothie": ["Smoothies are healthy!", "Blended goodness!", "Fruity!"],
    "latte": ["Lattes are smooth!", "Coffee culture!", "Espresso and milk!"],
    "espresso": ["Espresso is strong!", "Coffee shot!", "Energy boost!"],
    "cappuccino": ["Cappuccinos are frothy!", "Italian coffee!", "Morning ritual!"],
    "cocktail": ["Cocktails are festive!", "Mixed drinks!", "Cheers!"],
    "whiskey": ["Whiskey is refined!", "Aged spirits!", "On the rocks!"],
    "vodka": ["Vodka is versatile!", "Spirits!", "Mixable!"],
    "rum": ["Rum is tropical!", "Caribbean vibes!", "Pirates!"],
    "champagne": ["Champagne celebrates!", "Bubbles!", "Special occasions!"],
    "lemonade": ["Lemonade is refreshing!", "Summer drink!", "Sweet and sour!"],
    "mocktail": ["Mocktails are fun!", "Non-alcoholic!", "Everyone can enjoy!"],
    
    # Food Preparation
    "bake": ["Baking uses ovens!", "Desserts!", "Bread!"],
    "fry": ["Frying uses oil!", "Crispy!", "Quick cooking!"],
    "grill": ["Grilling chars!", "BBQ!", "Smoky flavor!"],
    "roast": ["Roasting is slow!", "Ovens!", "Tender meat!"],
    "boil": ["Boiling uses water!", "Hot!", "Pasta!"],
    "steam": ["Steaming is healthy!", "Vegetables!", "Moist heat!"],
    "saute": ["Sauteing is quick!", "Pan cooking!", "Flavor!"],
    "simmer": ["Simmering is gentle!", "Low heat!", "Soups!"],
    "blend": ["Blending mixes!", "Smoothies!", "Creamy!"],
    "chop": ["Chopping cuts!", "Knife skills!", "Prep!"],
    "slice": ["Slicing is precise!", "Thin cuts!", "Presentation!"],
    "dice": ["Dicing makes cubes!", "Even pieces!", "Cooking prep!"],
    "mince": ["Mincing is fine!", "Tiny pieces!", "Garlic!"],
    "marinate": ["Marinating adds flavor!", "Soaking!", "Tenderizing!"],
    "season": ["Seasoning enhances!", "Spices!", "Flavor!"],
    "garnish": ["Garnishing decorates!", "Presentation!", "Final touch!"],
    "recipe": ["Recipes guide cooking!", "Instructions!", "Follow along!"],
    "ingredient": ["Ingredients make dishes!", "Components!", "Shopping list!"],
    "portion": ["Portions control size!", "Serving!", "Amount!"],
    "leftovers": ["Leftovers save food!", "Next day meal!", "No waste!"],
    
    # Wine & Spirits
    "cabernet": ["Cabernet is bold red!", "Full-bodied!", "Steak pairing!"],
    "merlot": ["Merlot is smooth red!", "Approachable!", "Fruit forward!"],
    "pinot noir": ["Pinot Noir is light red!", "Elegant!", "Burgundy!"],
    "syrah": ["Syrah is spicy red!", "Bold!", "Shiraz in Australia!"],
    "malbec": ["Malbec is Argentine!", "Bold red!", "Smoky!"],
    "zinfandel": ["Zinfandel is jammy!", "California!", "Bold!"],
    "sangiovese": ["Sangiovese is Italian!", "Chianti!", "Tomato friendly!"],
    "tempranillo": ["Tempranillo is Spanish!", "Rioja!", "Leather notes!"],
    "chardonnay": ["Chardonnay is popular white!", "Oaky or crisp!", "Versatile!"],
    "sauvignon blanc": ["Sauvignon Blanc is crisp!", "Citrusy!", "Refreshing!"],
    "pinot grigio": ["Pinot Grigio is light!", "Italian!", "Easy drinking!"],
    "riesling": ["Riesling is aromatic!", "German!", "Sweet to dry!"],
    "moscato": ["Moscato is sweet!", "Bubbly!", "Dessert wine!"],
    "prosecco": ["Prosecco is Italian bubbles!", "Affordable!", "Aperitif!"],
    "cava": ["Cava is Spanish sparkling!", "Budget friendly!", "Refreshing!"],
    "rosé": ["Rosé is pink!", "Summer wine!", "Versatile!"],
    "port": ["Port is fortified!", "Portuguese!", "Dessert wine!"],
    "sherry": ["Sherry is Spanish fortified!", "Dry to sweet!", "Tapas!"],
    "vermouth": ["Vermouth is aromatized!", "Cocktails!", "Martinis!"],
    "cognac": ["Cognac is French brandy!", "Aged!", "Sipping!"],
    "brandy": ["Brandy is distilled wine!", "Warming!", "After dinner!"],
    "bourbon": ["Bourbon is American whiskey!", "Corn based!", "Kentucky!"],
    "scotch": ["Scotch is Scottish whisky!", "Smoky!", "Single malt!"],
    "irish whiskey": ["Irish whiskey is smooth!", "Triple distilled!", "Easy drinking!"],
    "rye whiskey": ["Rye whiskey is spicy!", "American!", "Manhattan!"],
    "tequila": ["Tequila is Mexican!", "Agave!", "Margaritas!"],
    "mezcal": ["Mezcal is smoky!", "Agave!", "Artisanal!"],
    "gin": ["Gin is botanical!", "Juniper!", "G&T!"],
    "sake": ["Sake is rice wine!", "Japanese!", "Warm or cold!"],
    "soju": ["Soju is Korean!", "Clear spirit!", "Popular!"],
    "absinthe": ["Absinthe is green!", "Anise flavored!", "The green fairy!"],
    "amaretto": ["Amaretto is almond liqueur!", "Italian!", "Sweet!"],
    "kahlua": ["Kahlúa is coffee liqueur!", "Mexican!", "Espresso martini!"],
    "baileys": ["Baileys is Irish cream!", "Creamy!", "Coffee pairing!"],
    "limoncello": ["Limoncello is lemon liqueur!", "Italian!", "Digestif!"],
    "sambuca": ["Sambuca is anise liqueur!", "Italian!", "Coffee beans!"],
    "triple sec": ["Triple sec is orange liqueur!", "Cocktails!", "Margaritas!"],
    "cointreau": ["Cointreau is orange liqueur!", "French!", "Premium!"],
    "grand marnier": ["Grand Marnier is orange cognac!", "French!", "Luxurious!"],
    
    # Coffee & Tea
    "americano": ["Americano is diluted espresso!", "Like drip!", "Smooth!"],
    "mocha": ["Mochas have chocolate!", "Coffee and cocoa!", "Sweet!"],
    "macchiato": ["Macchiatos are stained!", "Espresso marked!", "Strong!"],
    "cortado": ["Cortados are balanced!", "Spanish!", "Cut with milk!"],
    "flatwhite": ["Flat whites are velvety!", "Australian!", "Microfoam!"],
    "coldbrew": ["Cold brew is smooth!", "Steeped cold!", "Less acidic!"],
    "nitro": ["Nitro coffee is creamy!", "Nitrogen infused!", "Smooth!"],
    "pourover": ["Pour over is precise!", "Manual brewing!", "Clean flavor!"],
    "frenchpress": ["French press is full-bodied!", "Immersion!", "Rich!"],
    "aeropress": ["Aeropress is versatile!", "Pressure!", "Quick!"],
    "turkish": ["Turkish coffee is strong!", "Unfiltered!", "Traditional!"],
    "vietnamese": ["Vietnamese coffee is sweet!", "Condensed milk!", "Strong!"],
    "affogato": ["Affogato has ice cream!", "Espresso over gelato!", "Dessert!"],
    "greentea": ["Green tea is healthy!", "Antioxidants!", "Japanese!"],
    "blacktea": ["Black tea is robust!", "Caffeine!", "English breakfast!"],
    "oolong": ["Oolong is between green and black!", "Taiwanese!", "Floral!"],
    "whitetea": ["White tea is delicate!", "Minimal processing!", "Subtle!"],
    "chamomile": ["Chamomile is calming!", "Herbal!", "Sleepy time!"],
    "peppermint": ["Peppermint is refreshing!", "Herbal!", "Digestive!"],
    "earl grey": ["Earl Grey has bergamot!", "British!", "Citrusy!"],
    "chai": ["Chai is spiced!", "Indian!", "Warming!"],
    "matcha": ["Matcha is powdered green tea!", "Japanese!", "Vibrant!"],
    "rooibos": ["Rooibos is South African!", "Red bush!", "Caffeine-free!"],
    "hibiscus": ["Hibiscus tea is tart!", "Red!", "Refreshing!"],
    "ginger": ["Ginger tea is warming!", "Spicy!", "Soothing!"],
    "turmeric": ["Turmeric tea is golden!", "Anti-inflammatory!", "Healthy!"],
    "boba": ["Boba has tapioca pearls!", "Bubble tea!", "Fun to drink!"],
    
    # Herbs & Spices
    "basil": ["Basil is aromatic!", "Italian cuisine!", "Pesto!"],
    "oregano": ["Oregano is earthy!", "Mediterranean!", "Pizza!"],
    "thyme": ["Thyme is subtle!", "French cooking!", "Roasts!"],
    "rosemary": ["Rosemary is piney!", "Lamb pairing!", "Potatoes!"],
    "sage": ["Sage is earthy!", "Thanksgiving!", "Butter!"],
    "mint": ["Mint is refreshing!", "Mojitos!", "Lamb!"],
    "cilantro": ["Cilantro is divisive!", "Love it or hate it!", "Mexican!"],
    "parsley": ["Parsley is fresh!", "Garnish!", "Versatile!"],
    "dill": ["Dill is feathery!", "Pickles!", "Salmon!"],
    "chives": ["Chives are mild onion!", "Garnish!", "Potatoes!"],
    "tarragon": ["Tarragon is anise-like!", "French!", "Chicken!"],
    "bay leaf": ["Bay leaves are aromatic!", "Soups!", "Remove before serving!"],
    "cumin": ["Cumin is earthy!", "Mexican!", "Indian!"],
    "coriander": ["Coriander is citrusy!", "Cilantro seeds!", "Curry!"],
    "turmeric": ["Turmeric is golden!", "Anti-inflammatory!", "Curry!"],
    "paprika": ["Paprika is red pepper!", "Hungarian!", "Color!"],
    "cayenne": ["Cayenne is hot!", "Heat!", "Spicy!"],
    "chili powder": ["Chili powder is blend!", "Mexican!", "Heat!"],
    "crushed red pepper": ["Crushed red pepper adds heat!", "Pizza topping!", "Spicy!"],
    "black pepper": ["Black pepper is essential!", "King of spices!", "Universal!"],
    "white pepper": ["White pepper is milder!", "Light sauces!", "Subtle!"],
    "nutmeg": ["Nutmeg is warm!", "Baking!", "Eggnog!"],
    "cinnamon": ["Cinnamon is sweet and warm!", "Baking!", "Fall flavors!"],
    "cloves": ["Cloves are intense!", "Holiday baking!", "Ham!"],
    "allspice": ["Allspice tastes like many!", "Caribbean!", "Warm!"],
    "cardamom": ["Cardamom is exotic!", "Indian!", "Chai!"],
    "star anise": ["Star anise is licorice-like!", "Asian cooking!", "Pho!"],
    "fennel seed": ["Fennel is anise-like!", "Italian sausage!", "Digestive!"],
    "mustard seed": ["Mustard seeds pop!", "Indian!", "Pickling!"],
    "caraway": ["Caraway is in rye bread!", "Earthy!", "European!"],
    "poppy seed": ["Poppy seeds are crunchy!", "Baking!", "Bagels!"],
    "sesame": ["Sesame is nutty!", "Asian!", "Tahini!"],
    "saffron": ["Saffron is expensive!", "Golden!", "Paella!"],
    "vanilla": ["Vanilla is sweet!", "Baking essential!", "Orchid!"],
    "garlic": ["Garlic is pungent!", "Essential!", "Flavor base!"],
    "onion powder": ["Onion powder is concentrated!", "Seasoning!", "Convenience!"],
    "garlic powder": ["Garlic powder is convenient!", "Seasoning!", "Pantry staple!"],
}
