"""Life, emotions, relationships, and personal topics"""

LIFE_EMOTIONS = {
    # Life & Emotions
    "happy": ["Happiness is wonderful!", "Stay positive!", "What makes you happy?"],
    "sad": ["I'm sorry you're sad.", "It's okay to feel down sometimes.", "Tomorrow is a new day!"],
    "angry": ["Anger is natural.", "Take a deep breath!", "I understand frustration."],
    "excited": ["Excitement is great!", "What are you excited about?", "That energy is contagious!"],
    "scared": ["Fear is natural.", "You're braver than you think!", "It's okay to be scared."],
    "bored": ["Boredom can spark creativity!", "Try something new!", "What interests you?"],
    "tired": ["Rest is important!", "Take care of yourself!", "Sleep well!"],
    "stressed": ["Stress can be managed!", "Take a break!", "Deep breaths help!"],
    "love": ["Love is beautiful!", "Love makes the world go round!", "Such a powerful emotion!"],
    "hate": ["Hate is heavy.", "Try to let go of negativity.", "Focus on positivity!"],
    "life": ["Life is an adventure!", "What a journey!", "Make the most of it!"],
    "death": ["Death is a difficult topic.", "It's part of life.", "Cherish your time."],
    "friend": ["Friends are treasures!", "Friendship is important!", "Good friends are rare!"],
    "family": ["Family is everything!", "Family bonds are strong!", "Cherish your family!"],
    "relationship": ["Relationships take work!", "Communication is key!", "Love and respect!"],
    "home": ["Home is where the heart is!", "Comfort zone!", "A place of peace!"],
    
    # More Emotions & Feelings
    "joy": ["Joy is pure!", "Happiness!", "Wonderful feeling!"],
    "peace": ["Peace is calming!", "Tranquility!", "Inner harmony!"],
    "hope": ["Hope is powerful!", "Optimism!", "Better tomorrow!"],
    "fear": ["Fear is natural!", "Overcome it!", "Courage!"],
    "anxiety": ["Anxiety is common!", "Breathe!", "You're not alone!"],
    "depression": ["Depression is serious!", "Seek help!", "You matter!"],
    "lonely": ["Loneliness hurts!", "Reach out!", "You're not alone!"],
    "lonely": ["Loneliness is temporary!", "Connect with others!", "You're valued!"],
    "nervous": ["Nervousness is normal!", "Butterflies!", "You'll be fine!"],
    "confident": ["Confidence is attractive!", "Believe in yourself!", "You've got this!"],
    "proud": ["Pride feels good!", "Accomplishment!", "Well deserved!"],
    "grateful": ["Gratitude is powerful!", "Thankfulness!", "Appreciate life!"],
    "jealous": ["Jealousy is natural!", "Focus on yourself!", "Compare less!"],
    "embarrassed": ["Embarrassment passes!", "Everyone experiences it!", "Laugh it off!"],
    "ashamed": ["Shame is heavy!", "Forgive yourself!", "Learn and grow!"],
    "guilty": ["Guilt can teach!", "Make amends!", "Learn from mistakes!"],
    "confused": ["Confusion is temporary!", "Seek clarity!", "It's okay to not know!"],
    "frustrated": ["Frustration is normal!", "Take a break!", "Deep breaths!"],
    "disappointed": ["Disappointment hurts!", "New opportunities!", "Keep going!"],
    "surprised": ["Surprises are exciting!", "Unexpected!", "Life's twists!"],
    "curious": ["Curiosity drives learning!", "Ask questions!", "Explore!"],
    "nostalgic": ["Nostalgia is bittersweet!", "Good memories!", "The past!"],
    "content": ["Contentment is peace!", "Satisfied!", "Enough!"],
    "inspired": ["Inspiration fuels action!", "Motivated!", "Create!"],
    "motivated": ["Motivation drives success!", "Goal-oriented!", "Keep going!"],
    "overwhelmed": ["Overwhelm happens!", "One step at a time!", "Breathe!"],
    "relaxed": ["Relaxation is healing!", "Calm!", "At peace!"],
    "bittersweet": ["Bittersweet is complex!", "Mixed feelings!", "Life!"],
    "empathy": ["Empathy connects us!", "Understanding!", "Compassion!"],
    "sympathy": ["Sympathy shows care!", "Compassion!", "Support!"],
    "compassion": ["Compassion is kindness!", "Caring!", "Humanity!"],
    "mindfulness": ["Mindfulness is awareness!", "Present moment!", "Meditation!"],
    "meditation": ["Meditation calms mind!", "Inner peace!", "Focus!"],
    "therapy": ["Therapy helps!", "Mental health!", "Professional support!"],
    "selfcare": ["Self-care is essential!", "Take care of you!", "Health!"],
    "wellness": ["Wellness is holistic!", "Mind and body!", "Balance!"],
    "mental health": ["Mental health matters!", "Take care!", "No stigma!"],
    "healing": ["Healing takes time!", "Recovery!", "Patience!"],
    
    # Relationships
    "marriage": ["Marriage is commitment!", "Partnership!", "Love!"],
    "wedding": ["Weddings celebrate love!", "Special day!", "Beautiful!"],
    "divorce": ["Divorce is difficult!", "New beginnings!", "Support matters!"],
    "dating": ["Dating is exciting!", "Meeting people!", "Romance!"],
    "boyfriend": ["Boyfriends are partners!", "Romance!", "Relationship!"],
    "girlfriend": ["Girlfriends are partners!", "Romance!", "Relationship!"],
    "husband": ["Husbands are life partners!", "Marriage!", "Commitment!"],
    "wife": ["Wives are life partners!", "Marriage!", "Commitment!"],
    "partner": ["Partners share life!", "Together!", "Support!"],
    "crush": ["Crushes are exciting!", "Butterflies!", "New feelings!"],
    "breakup": ["Breakups are hard!", "Healing takes time!", "New beginnings!"],
    "single": ["Single life has freedom!", "Independence!", "Self-discovery!"],
    "couple": ["Couples share life!", "Together!", "Partnership!"],
    "romance": ["Romance is sweet!", "Love!", "Connection!"],
    "flirt": ["Flirting is fun!", "Playful!", "Chemistry!"],
    "kiss": ["Kisses are sweet!", "Affection!", "Love!"],
    "hug": ["Hugs are comforting!", "Warmth!", "Connection!"],
    "anniversary": ["Anniversaries celebrate!", "Milestones!", "Memories!"],
    "valentine": ["Valentine's Day is romantic!", "Love day!", "Sweet!"],
    "soulmate": ["Soulmates are special!", "Deep connection!", "Meant to be!"],
    "heartbreak": ["Heartbreak hurts!", "Time heals!", "You'll be okay!"],
    "trust": ["Trust is foundation!", "Essential!", "Built over time!"],
    "loyalty": ["Loyalty is valued!", "Faithfulness!", "True!"],
    "communication": ["Communication is key!", "Talk openly!", "Understanding!"],
    "compromise": ["Compromise builds relationships!", "Middle ground!", "Together!"],
    "argument": ["Arguments happen!", "Resolve respectfully!", "Communication!"],
    "forgiveness": ["Forgiveness frees you!", "Let go!", "Peace!"],
    "apology": ["Apologies matter!", "Sorry!", "Acknowledgment!"],
    
    # Colors
    "color": ["Colors brighten life!", "Rainbow!", "Visual!"],
    "red": ["Red is passionate!", "Bold!", "Energetic!"],
    "blue": ["Blue is calming!", "Ocean and sky!", "Peaceful!"],
    "green": ["Green is natural!", "Growth!", "Nature!"],
    "yellow": ["Yellow is cheerful!", "Sunshine!", "Happy!"],
    "orange": ["Orange is energetic!", "Vibrant!", "Warm!"],
    "purple": ["Purple is royal!", "Creative!", "Mysterious!"],
    "pink": ["Pink is sweet!", "Soft!", "Romantic!"],
    "black": ["Black is sophisticated!", "Elegant!", "Classic!"],
    "white": ["White is pure!", "Clean!", "Simple!"],
    "brown": ["Brown is earthy!", "Natural!", "Warm!"],
    "gray": ["Gray is neutral!", "Balanced!", "Sophisticated!"],
    "gold": ["Gold is luxurious!", "Precious!", "Shiny!"],
    "silver": ["Silver is elegant!", "Sleek!", "Modern!"],
    
    # Body & Health
    "health": ["Health is wealth!", "Take care!", "Essential!"],
    "body": ["Bodies are amazing!", "Take care of it!", "Health!"],
    "sleep": ["Sleep is essential!", "Rest well!", "Recharge!"],
    "dream": ["Dreams are mysterious!", "Sleep adventures!", "Fascinating!"],
    "medicine": ["Medicine heals!", "Healthcare!", "Treatment!"],
    "doctor": ["Doctors help heal!", "Healthcare!", "Expertise!"],
    "hospital": ["Hospitals provide care!", "Medical!", "Health!"],
    "sick": ["Being sick is no fun!", "Rest up!", "Get well soon!"],
    "pain": ["Pain is difficult!", "Healing!", "Take care!"],
    "headache": ["Headaches are no fun!", "Rest!", "Pain relief!"],
    "cold": ["Colds are common!", "Rest and fluids!", "Get well!"],
    "flu": ["Flu is worse than cold!", "Rest up!", "Recovery!"],
    "allergy": ["Allergies are annoying!", "Sneezing!", "Antihistamines!"],
    "vaccine": ["Vaccines protect!", "Prevention!", "Healthcare!"],
    "surgery": ["Surgery can be scary!", "Medical procedure!", "Recovery!"],
    "therapy": ["Therapy helps!", "Mental and physical!", "Healing!"],
    "diet": ["Diet affects health!", "Nutrition!", "Balance!"],
    "nutrition": ["Nutrition fuels body!", "Healthy eating!", "Vitamins!"],
    "vitamin": ["Vitamins are essential!", "Supplements!", "Health!"],
    "protein": ["Protein builds muscle!", "Nutrition!", "Essential!"],
    "carb": ["Carbs give energy!", "Nutrition!", "Fuel!"],
    "fat": ["Fats are needed!", "Good and bad types!", "Nutrition!"],
    "calorie": ["Calories measure energy!", "Nutrition!", "Balance!"],
    "weight": ["Weight management!", "Health!", "Balance!"],
    "muscle": ["Muscles provide strength!", "Exercise!", "Fitness!"],
    "bone": ["Bones support body!", "Calcium!", "Structure!"],
    "heart": ["Heart pumps blood!", "Cardio!", "Essential organ!"],
    "brain": ["Brain controls everything!", "Thinking!", "Amazing organ!"],
    "blood": ["Blood carries oxygen!", "Essential!", "Life force!"],
    "skin": ["Skin protects!", "Largest organ!", "Care for it!"],
    "eye": ["Eyes see the world!", "Vision!", "Precious!"],
    "ear": ["Ears hear sounds!", "Hearing!", "Balance!"],
    "nose": ["Nose smells!", "Breathing!", "Senses!"],
    "mouth": ["Mouth speaks and eats!", "Communication!", "Taste!"],
    "teeth": ["Teeth chew food!", "Dental care!", "Smile!"],
    "hair": ["Hair grows!", "Style!", "Personal expression!"],
    "hand": ["Hands do work!", "Touch!", "Versatile!"],
    "foot": ["Feet support us!", "Walking!", "Balance!"],
    "leg": ["Legs move us!", "Walking!", "Running!"],
    "arm": ["Arms reach and hold!", "Versatile!", "Strength!"],
    
    # Numbers & Time
    "number": ["Numbers are everywhere!", "Math!", "Counting!"],
    "time": ["Time flies!", "Precious resource!", "Make it count!"],
    "year": ["Years mark time!", "Seasons!", "Growth!"],
    "month": ["Months organize year!", "Calendar!", "Planning!"],
    "week": ["Weeks structure life!", "Seven days!", "Routine!"],
    "day": ["Days are opportunities!", "24 hours!", "Make it count!"],
    "hour": ["Hours are precious!", "60 minutes!", "Time management!"],
    "minute": ["Minutes add up!", "60 seconds!", "Quick!"],
    "second": ["Seconds are instant!", "Brief moments!", "Quick!"],
    "morning": ["Mornings are fresh starts!", "New day!", "Rise and shine!"],
    "afternoon": ["Afternoons are productive!", "Midday!", "Keep going!"],
    "evening": ["Evenings wind down!", "Relaxation!", "Dinner time!"],
    "night": ["Night is for rest!", "Sleep!", "Stars!"],
    "today": ["Today is a gift!", "Present!", "Make it count!"],
    "tomorrow": ["Tomorrow brings hope!", "Future!", "New day!"],
    "yesterday": ["Yesterday is past!", "Memories!", "Learn from it!"],
    "future": ["The future is exciting!", "Possibilities!", "Hope!"],
    "past": ["The past teaches!", "Memories!", "History!"],
    "present": ["The present is now!", "Be here!", "Mindfulness!"],
    "birthday": ["Birthdays celebrate life!", "Another year!", "Cake!"],
    "holiday": ["Holidays are special!", "Celebrations!", "Time off!"],
    "weekend": ["Weekends are freedom!", "Rest!", "Fun!"],
    "vacation": ["Vacations recharge!", "Travel!", "Relaxation!"],
    "schedule": ["Schedules organize life!", "Planning!", "Time management!"],
    "deadline": ["Deadlines motivate!", "Due dates!", "Pressure!"],
    "appointment": ["Appointments are commitments!", "Calendar!", "Planning!"],
    "calendar": ["Calendars track time!", "Organization!", "Planning!"],
    "clock": ["Clocks show time!", "Ticking!", "Timekeeping!"],
    "watch": ["Watches are convenient!", "Time on wrist!", "Fashion and function!"],
    "alarm": ["Alarms wake us!", "Reminders!", "Time!"],
}
