"""Miscellaneous categories: shopping, hobbies, home, materials, etc."""

MISC = {
    # Shopping & Objects
    "shopping": ["Shopping is fun!", "What do you shop for?", "Retail therapy!"],
    "shop": ["Shops have everything!", "What are you looking for?", "Browsing!"],
    "store": ["Stores offer variety!", "What kind?", "Retail!"],
    "buy": ["Buying is exciting!", "What do you want?", "Purchase!"],
    "sell": ["Selling provides income!", "What are you selling?", "Commerce!"],
    "price": ["Prices vary!", "Expensive or affordable?", "Cost!"],
    "cheap": ["Cheap saves money!", "Budget!", "Affordable!"],
    "expensive": ["Expensive means quality!", "Or not!", "Pricey!"],
    "discount": ["Discounts save money!", "Sales!", "Deals!"],
    "sale": ["Sales are great!", "Bargains!", "Shop now!"],
    "deal": ["Deals save money!", "Great finds!", "Value!"],
    "coupon": ["Coupons give discounts!", "Savings!", "Clip them!"],
    "gift": ["Gifts show love!", "Presents!", "Thoughtful!"],
    "present": ["Presents bring joy!", "Gifts!", "Occasions!"],
    "toy": ["Toys are fun!", "Play!", "Kids love them!"],
    "clothes": ["Clothes express style!", "Fashion!", "Wardrobe!"],
    "fashion": ["Fashion is expression!", "Style!", "Trends!"],
    "style": ["Style is personal!", "Fashion!", "Expression!"],
    "dress": ["Dresses are elegant!", "Clothing!", "Occasions!"],
    "shirt": ["Shirts are versatile!", "Tops!", "Style!"],
    "pants": ["Pants are everyday wear!", "Bottoms!", "Comfortable!"],
    "jeans": ["Jeans are classic!", "Denim!", "Casual!"],
    "shoes": ["Shoes complete outfits!", "Footwear!", "Comfort!"],
    "sneakers": ["Sneakers are comfortable!", "Athletic!", "Casual!"],
    "boots": ["Boots are sturdy!", "Footwear!", "Weather!"],
    "jacket": ["Jackets provide warmth!", "Outerwear!", "Style!"],
    "coat": ["Coats keep warm!", "Winter!", "Outerwear!"],
    "hat": ["Hats accessorize!", "Headwear!", "Sun protection!"],
    "watch": ["Watches tell time!", "Accessory!", "Style!"],
    "jewelry": ["Jewelry sparkles!", "Accessories!", "Adornment!"],
    "ring": ["Rings symbolize!", "Jewelry!", "Commitment!"],
    "necklace": ["Necklaces adorn necks!", "Jewelry!", "Beautiful!"],
    "bracelet": ["Bracelets decorate wrists!", "Jewelry!", "Accessories!"],
    "earring": ["Earrings frame faces!", "Jewelry!", "Style!"],
    "bag": ["Bags carry things!", "Handbags!", "Utility!"],
    "purse": ["Purses hold essentials!", "Handbags!", "Fashion!"],
    "wallet": ["Wallets hold cards and cash!", "Accessory!", "Essential!"],
    "glasses": ["Glasses help see!", "Eyewear!", "Vision!"],
    "sunglasses": ["Sunglasses protect eyes!", "Style!", "UV protection!"],
    
    # Home & Household
    "house": ["Houses are homes!", "Living spaces!", "Shelter!"],
    "apartment": ["Apartments are convenient!", "City living!", "Rental!"],
    "room": ["Rooms serve purposes!", "Spaces!", "Interior!"],
    "kitchen": ["Kitchens are for cooking!", "Heart of home!", "Meals!"],
    "bedroom": ["Bedrooms are for rest!", "Sleep!", "Private!"],
    "bathroom": ["Bathrooms are essential!", "Hygiene!", "Privacy!"],
    "living room": ["Living rooms are social!", "Family time!", "Relaxation!"],
    "dining room": ["Dining rooms are for meals!", "Eating together!", "Formal!"],
    "garage": ["Garages store cars!", "Storage!", "Workshop!"],
    "yard": ["Yards offer outdoor space!", "Garden!", "Play!"],
    "garden": ["Gardens grow beauty!", "Plants!", "Peaceful!"],
    "patio": ["Patios are outdoor living!", "Relaxation!", "BBQ!"],
    "deck": ["Decks extend living space!", "Outdoor!", "Wood!"],
    "balcony": ["Balconies offer views!", "Outdoor space!", "Fresh air!"],
    "basement": ["Basements are underground!", "Storage!", "Extra space!"],
    "attic": ["Attics are under roofs!", "Storage!", "Hidden space!"],
    "closet": ["Closets store clothes!", "Organization!", "Space!"],
    "laundry": ["Laundry cleans clothes!", "Chore!", "Necessary!"],
    
    # Furniture
    "furniture": ["Furniture fills spaces!", "Home!", "Comfort!"],
    "chair": ["Chairs are for sitting!", "Seating!", "Comfort!"],
    "table": ["Tables are surfaces!", "Dining!", "Work!"],
    "desk": ["Desks are for work!", "Office!", "Study!"],
    "couch": ["Couches are comfy!", "Living room!", "Relaxation!"],
    "sofa": ["Sofas seat many!", "Living room!", "Comfort!"],
    "bed": ["Beds are for sleep!", "Bedroom!", "Rest!"],
    "mattress": ["Mattresses support sleep!", "Comfort!", "Quality!"],
    "pillow": ["Pillows cushion heads!", "Sleep!", "Comfort!"],
    "blanket": ["Blankets keep warm!", "Cozy!", "Comfort!"],
    "lamp": ["Lamps provide light!", "Lighting!", "Decor!"],
    "shelf": ["Shelves store things!", "Organization!", "Display!"],
    "bookshelf": ["Bookshelves hold books!", "Storage!", "Decor!"],
    "cabinet": ["Cabinets store items!", "Kitchen!", "Organization!"],
    "drawer": ["Drawers slide out!", "Storage!", "Organization!"],
    "mirror": ["Mirrors reflect!", "Bathroom!", "Decor!"],
    "rug": ["Rugs cover floors!", "Decor!", "Warmth!"],
    "curtain": ["Curtains cover windows!", "Privacy!", "Decor!"],
    "blinds": ["Blinds control light!", "Windows!", "Privacy!"],
    "nightstand": ["Nightstands hold bedside items!", "Bedroom!", "Convenience!"],
    "dresser": ["Dressers store clothes!", "Bedroom!", "Organization!"],
    "wardrobe": ["Wardrobes hold clothing!", "Storage!", "Organization!"],
    "armchair": ["Armchairs are cozy!", "Seating!", "Comfort!"],
    "recliner": ["Recliners lean back!", "Comfort!", "Relaxation!"],
    "ottoman": ["Ottomans rest feet!", "Footrest!", "Comfort!"],
    "bench": ["Benches seat multiple!", "Seating!", "Outdoor!"],
    "stool": ["Stools are backless seats!", "Bar!", "Kitchen!"],
    "coffee table": ["Coffee tables are central!", "Living room!", "Decor!"],
    "end table": ["End tables flank sofas!", "Side tables!", "Convenience!"],
    "dining table": ["Dining tables gather family!", "Meals!", "Together!"],
    "tv stand": ["TV stands hold screens!", "Entertainment!", "Media!"],
    
    # Tools
    "tool": ["Tools help build!", "Equipment!", "Handy!"],
    "hammer": ["Hammers drive nails!", "Building!", "Essential!"],
    "screwdriver": ["Screwdrivers turn screws!", "Fastening!", "Essential!"],
    "wrench": ["Wrenches turn bolts!", "Mechanical!", "Plumbing!"],
    "pliers": ["Pliers grip things!", "Bending!", "Holding!"],
    "drill": ["Drills make holes!", "Power tool!", "Building!"],
    "saw": ["Saws cut materials!", "Wood!", "Metal!"],
    "tape measure": ["Tape measures lengths!", "Measuring!", "Accuracy!"],
    "level": ["Levels check flatness!", "Straight!", "Building!"],
    "ladder": ["Ladders reach heights!", "Climbing!", "Safety!"],
    "toolbox": ["Toolboxes organize tools!", "Storage!", "Portable!"],
    "nail": ["Nails fasten wood!", "Building!", "Hammered!"],
    "screw": ["Screws fasten tightly!", "Building!", "Twisted!"],
    "bolt": ["Bolts are strong fasteners!", "Mechanical!", "Nuts!"],
    "nut": ["Nuts secure bolts!", "Fastening!", "Mechanical!"],
    "washer": ["Washers distribute load!", "Fastening!", "Flat!"],
    "glue": ["Glue bonds materials!", "Adhesive!", "Sticky!"],
    "tape": ["Tape holds things!", "Adhesive!", "Versatile!"],
    "sandpaper": ["Sandpaper smooths surfaces!", "Finishing!", "Grit!"],
    "paintbrush": ["Paintbrushes apply paint!", "Painting!", "Art!"],
    "roller": ["Rollers cover walls fast!", "Painting!", "Efficiency!"],
    
    # Vehicles
    "car": ["Cars provide freedom!", "Driving!", "Transportation!"],
    "truck": ["Trucks haul things!", "Heavy duty!", "Work!"],
    "motorcycle": ["Motorcycles are thrilling!", "Two wheels!", "Freedom!"],
    "bicycle": ["Bicycles are healthy!", "Pedal power!", "Eco-friendly!"],
    "bus": ["Buses carry many!", "Public transit!", "Commuting!"],
    "train": ["Trains are efficient!", "Rail!", "Travel!"],
    "airplane": ["Airplanes fly!", "Aviation!", "Travel!"],
    "boat": ["Boats float!", "Water!", "Sailing!"],
    "ship": ["Ships cross oceans!", "Large vessels!", "Cargo!"],
    "helicopter": ["Helicopters hover!", "Aviation!", "Vertical!"],
    "subway": ["Subways are underground trains!", "Urban transit!", "Fast!"],
    "taxi": ["Taxis give rides!", "Transportation!", "Convenient!"],
    "uber": ["Uber is rideshare!", "App!", "Convenient!"],
    "scooter": ["Scooters are nimble!", "Urban!", "Fun!"],
    "van": ["Vans carry more!", "Cargo!", "Family!"],
    "suv": ["SUVs are versatile!", "Sport utility!", "Space!"],
    "sedan": ["Sedans are practical!", "Four doors!", "Common!"],
    "coupe": ["Coupes are sporty!", "Two doors!", "Style!"],
    "convertible": ["Convertibles have open tops!", "Wind in hair!", "Summer!"],
    "electric car": ["Electric cars are future!", "Clean!", "Tesla!"],
    "hybrid": ["Hybrids use both!", "Fuel efficient!", "Eco!"],
    
    # Materials
    "material": ["Materials build things!", "Substances!", "Construction!"],
    "wood": ["Wood is natural!", "Trees!", "Building!"],
    "metal": ["Metal is strong!", "Durable!", "Industrial!"],
    "plastic": ["Plastic is versatile!", "Synthetic!", "Common!"],
    "glass": ["Glass is transparent!", "Windows!", "Fragile!"],
    "paper": ["Paper comes from trees!", "Writing!", "Packaging!"],
    "fabric": ["Fabric makes clothes!", "Textiles!", "Soft!"],
    "leather": ["Leather is durable!", "Animal hide!", "Quality!"],
    "rubber": ["Rubber is flexible!", "Elastic!", "Tires!"],
    "concrete": ["Concrete is strong!", "Building!", "Foundations!"],
    "ceramic": ["Ceramic is fired clay!", "Pottery!", "Tiles!"],
    "stone": ["Stone is natural!", "Building!", "Durable!"],
    "brick": ["Brick is classic!", "Building!", "Walls!"],
    "cotton": ["Cotton is soft!", "Natural fiber!", "Clothing!"],
    "wool": ["Wool is warm!", "Sheep!", "Sweaters!"],
    "silk": ["Silk is luxurious!", "Smooth!", "Elegant!"],
    "linen": ["Linen is breathable!", "Flax!", "Summer!"],
    "nylon": ["Nylon is synthetic!", "Durable!", "Stretchy!"],
    "polyester": ["Polyester is common!", "Synthetic!", "Durable!"],
    "denim": ["Denim is sturdy!", "Jeans!", "Cotton!"],
    "velvet": ["Velvet is soft!", "Luxurious!", "Texture!"],
    "suede": ["Suede is soft leather!", "Texture!", "Delicate!"],
    "canvas": ["Canvas is sturdy fabric!", "Art!", "Bags!"],
    "cashmere": ["Cashmere is luxury!", "Soft goat hair!", "Expensive!"],
    "fleece": ["Fleece is warm!", "Synthetic!", "Cozy!"],
    
    # Shapes
    "shape": ["Shapes are forms!", "Geometry!", "Visual!"],
    "circle": ["Circles are round!", "No corners!", "Continuous!"],
    "square": ["Squares have equal sides!", "Four corners!", "Balanced!"],
    "triangle": ["Triangles have three sides!", "Strongest shape!", "Geometry!"],
    "rectangle": ["Rectangles have four sides!", "Longer sides!", "Common!"],
    "oval": ["Ovals are elongated circles!", "Egg-shaped!", "Smooth!"],
    "diamond": ["Diamonds are rotated squares!", "Sparkle!", "Shape!"],
    "star": ["Stars have points!", "Shining!", "Celestial!"],
    "heart": ["Hearts symbolize love!", "Romantic!", "Shape!"],
    "sphere": ["Spheres are 3D circles!", "Balls!", "Round!"],
    "cube": ["Cubes are 3D squares!", "Boxes!", "Six faces!"],
    "cylinder": ["Cylinders are tubes!", "Cans!", "Round sides!"],
    "cone": ["Cones taper to point!", "Ice cream!", "3D!"],
    "pyramid": ["Pyramids have triangular faces!", "Egypt!", "Point top!"],
    "hexagon": ["Hexagons have six sides!", "Honeycombs!", "Efficient!"],
    "octagon": ["Octagons have eight sides!", "Stop signs!", "Shape!"],
    "pentagon": ["Pentagons have five sides!", "Building!", "Shape!"],
    
    # Directions & Measurements
    "direction": ["Directions guide us!", "Navigation!", "Where to go!"],
    "north": ["North is up!", "Direction!", "Compass!"],
    "south": ["South is down!", "Direction!", "Compass!"],
    "east": ["East is where sun rises!", "Direction!", "Orient!"],
    "west": ["West is where sun sets!", "Direction!", "Occident!"],
    "left": ["Left is one side!", "Direction!", "Port!"],
    "right": ["Right is other side!", "Direction!", "Starboard!"],
    "up": ["Up is overhead!", "Direction!", "Above!"],
    "down": ["Down is below!", "Direction!", "Under!"],
    "forward": ["Forward is ahead!", "Direction!", "Progress!"],
    "backward": ["Backward is behind!", "Direction!", "Reverse!"],
    "measurement": ["Measurements quantify!", "Size!", "Exact!"],
    "inch": ["Inches are small units!", "Imperial!", "Small!"],
    "foot": ["Feet are 12 inches!", "Imperial!", "Length!"],
    "yard": ["Yards are 3 feet!", "Imperial!", "Length!"],
    "mile": ["Miles are long!", "Distance!", "Travel!"],
    "meter": ["Meters are metric!", "Length!", "Standard!"],
    "centimeter": ["Centimeters are small!", "Metric!", "Precision!"],
    "kilometer": ["Kilometers are metric miles!", "Distance!", "Metric!"],
    "weight": ["Weight measures mass!", "Heavy or light!", "Scales!"],
    "pound": ["Pounds are weight units!", "Imperial!", "Heavy!"],
    "ounce": ["Ounces are smaller!", "Imperial!", "Lighter!"],
    "gram": ["Grams are metric weight!", "Small!", "Metric!"],
    "kilogram": ["Kilograms are metric pounds!", "Weight!", "Metric!"],
    "volume": ["Volume measures space!", "Liquid!", "Capacity!"],
    "gallon": ["Gallons are liquid volume!", "Imperial!", "Fuel!"],
    "liter": ["Liters are metric volume!", "Liquid!", "Metric!"],
    "cup": ["Cups measure cooking!", "Baking!", "Kitchen!"],
    "tablespoon": ["Tablespoons are cooking measures!", "Small amounts!", "Recipes!"],
    "teaspoon": ["Teaspoons are tiny!", "Cooking!", "Medicine!"],
    
    # Actions
    "action": ["Actions make things happen!", "Doing!", "Movement!"],
    "walk": ["Walking is basic movement!", "Exercise!", "Transportation!"],
    "run": ["Running is fast walking!", "Exercise!", "Speed!"],
    "jump": ["Jumping is leaping!", "Up!", "Fun!"],
    "swim": ["Swimming is in water!", "Exercise!", "Cool!"],
    "fly": ["Flying is through air!", "Birds!", "Planes!"],
    "drive": ["Driving operates vehicles!", "Cars!", "Travel!"],
    "ride": ["Riding is being transported!", "Bikes!", "Horses!"],
    "sit": ["Sitting is resting!", "Chairs!", "Relax!"],
    "stand": ["Standing is upright!", "Position!", "Waiting!"],
    "sleep": ["Sleeping is rest!", "Night!", "Dreams!"],
    "eat": ["Eating is consuming food!", "Nutrition!", "Meals!"],
    "drink": ["Drinking is consuming liquids!", "Hydration!", "Beverages!"],
    "talk": ["Talking is communication!", "Words!", "Conversation!"],
    "listen": ["Listening is hearing actively!", "Attention!", "Learning!"],
    "read": ["Reading is decoding text!", "Books!", "Learning!"],
    "write": ["Writing is putting words down!", "Communication!", "Expression!"],
    "think": ["Thinking is mental activity!", "Mind!", "Ideas!"],
    "feel": ["Feeling is emotion!", "Senses!", "Heart!"],
    "see": ["Seeing is visual!", "Eyes!", "Vision!"],
    "hear": ["Hearing is auditory!", "Ears!", "Sound!"],
    "touch": ["Touching is tactile!", "Hands!", "Feel!"],
    "smell": ["Smelling is olfactory!", "Nose!", "Scents!"],
    "taste": ["Tasting is gustatory!", "Tongue!", "Flavor!"],
    "laugh": ["Laughing is joy!", "Humor!", "Happy!"],
    "cry": ["Crying is emotion!", "Tears!", "Release!"],
    "smile": ["Smiling is happiness!", "Face!", "Friendly!"],
    "dance": ["Dancing is rhythmic movement!", "Music!", "Expression!"],
    "sing": ["Singing is vocal music!", "Voice!", "Melody!"],
    "play": ["Playing is fun activity!", "Games!", "Recreation!"],
    "work": ["Working is productive activity!", "Job!", "Effort!"],
    "rest": ["Resting is recuperation!", "Relax!", "Recovery!"],
    "create": ["Creating is making new!", "Art!", "Innovation!"],
    "destroy": ["Destroying is breaking down!", "Demolition!", "End!"],
    "build": ["Building is constructing!", "Creation!", "Development!"],
    "fix": ["Fixing is repairing!", "Maintenance!", "Solutions!"],
    "break": ["Breaking is damaging!", "Accidents!", "Force!"],
    "open": ["Opening is allowing access!", "Doors!", "Begin!"],
    "close": ["Closing is shutting!", "End!", "Doors!"],
    "start": ["Starting is beginning!", "Initiate!", "Go!"],
    "stop": ["Stopping is ceasing!", "End!", "Halt!"],
    "give": ["Giving is providing!", "Generosity!", "Share!"],
    "take": ["Taking is receiving!", "Accept!", "Grab!"],
    "send": ["Sending is transmitting!", "Mail!", "Messages!"],
    "receive": ["Receiving is getting!", "Accept!", "Arrive!"],
    "ask": ["Asking is questioning!", "Inquiry!", "Curiosity!"],
    "answer": ["Answering is responding!", "Reply!", "Solution!"],
    "help": ["Helping is assisting!", "Support!", "Aid!"],
    "teach": ["Teaching is instructing!", "Education!", "Share knowledge!"],
    "learn": ["Learning is acquiring knowledge!", "Education!", "Growth!"],
    "grow": ["Growing is developing!", "Expand!", "Progress!"],
    "change": ["Changing is transforming!", "Different!", "Evolution!"],
    "stay": ["Staying is remaining!", "Stable!", "Continue!"],
    "leave": ["Leaving is departing!", "Exit!", "Go!"],
    "come": ["Coming is arriving!", "Approach!", "Here!"],
    "go": ["Going is moving!", "Travel!", "Leave!"],
    "find": ["Finding is discovering!", "Search!", "Locate!"],
    "lose": ["Losing is misplacing!", "Gone!", "Search!"],
    "win": ["Winning is succeeding!", "Victory!", "Competition!"],
    "try": ["Trying is attempting!", "Effort!", "Endeavor!"],
    "succeed": ["Succeeding is achieving!", "Victory!", "Goals!"],
    "fail": ["Failing is not succeeding!", "Learn!", "Try again!"],
    
    # Hobbies
    "hobby": ["Hobbies enrich life!", "Interests!", "Passion!"],
    "craft": ["Crafts are handmade!", "DIY!", "Creative!"],
    "knitting": ["Knitting creates fabric!", "Yarn!", "Cozy!"],
    "sewing": ["Sewing joins fabric!", "Clothing!", "Repair!"],
    "painting": ["Painting creates art!", "Canvas!", "Colors!"],
    "drawing": ["Drawing is visual art!", "Pencils!", "Sketching!"],
    "sculpture": ["Sculptures are 3D art!", "Carving!", "Molding!"],
    "pottery": ["Pottery shapes clay!", "Ceramic!", "Wheel!"],
    "woodworking": ["Woodworking crafts wood!", "Carpentry!", "Building!"],
    "gardening": ["Gardening grows plants!", "Nature!", "Peaceful!"],
    "photography": ["Photography captures moments!", "Camera!", "Images!"],
    "collecting": ["Collecting gathers items!", "Stamps!", "Coins!"],
    "birdwatching": ["Birdwatching observes birds!", "Nature!", "Peaceful!"],
    "stargazing": ["Stargazing looks at stars!", "Night sky!", "Wonder!"],
    "writing": ["Writing expresses ideas!", "Words!", "Creative!"],
    "blogging": ["Blogging shares online!", "Content!", "Internet!"],
    "vlogging": ["Vlogging shares video!", "YouTube!", "Content!"],
    "puzzles": ["Puzzles challenge minds!", "Games!", "Thinking!"],
    "crossword": ["Crosswords test vocabulary!", "Puzzles!", "Words!"],
    "sudoku": ["Sudoku is number puzzle!", "Logic!", "Grids!"],
    "origami": ["Origami folds paper!", "Japanese!", "Art!"],
    "calligraphy": ["Calligraphy is beautiful writing!", "Art!", "Letters!"],
    "embroidery": ["Embroidery decorates fabric!", "Needlework!", "Design!"],
    "scrapbooking": ["Scrapbooking preserves memories!", "Photos!", "Creative!"],
    "model building": ["Model building creates miniatures!", "Kits!", "Detail!"],
    "astronomy": ["Amateur astronomy explores sky!", "Telescopes!", "Stars!"],
    "magic": ["Magic tricks amaze!", "Illusions!", "Performance!"],
    "juggling": ["Juggling is coordination!", "Balls!", "Skill!"],
    
    # Dance
    "dance": ["Dance is expression!", "Movement!", "Music!"],
    "ballet": ["Ballet is classical dance!", "Graceful!", "Technique!"],
    "hip hop": ["Hip hop is urban dance!", "Street!", "Energy!"],
    "salsa": ["Salsa is Latin dance!", "Partner!", "Rhythm!"],
    "tango": ["Tango is passionate!", "Argentine!", "Partner dance!"],
    "waltz": ["Waltz is elegant!", "Ballroom!", "1-2-3!"],
    "jazz": ["Jazz dance is rhythmic!", "Broadway!", "Style!"],
    "tap": ["Tap dance makes sounds!", "Shoes!", "Rhythm!"],
    "contemporary": ["Contemporary dance is modern!", "Expressive!", "Fluid!"],
    "breakdance": ["Breakdancing is acrobatic!", "B-boy!", "Street!"],
    "flamenco": ["Flamenco is Spanish!", "Passion!", "Guitar!"],
    "ballroom": ["Ballroom dance is formal!", "Partner!", "Elegant!"],
    "swing": ["Swing dance is lively!", "Jazz era!", "Fun!"],
    "line dance": ["Line dancing is group!", "Country!", "Synchronized!"],
    "belly dance": ["Belly dance is Middle Eastern!", "Movement!", "Costume!"],
    "folk dance": ["Folk dance is traditional!", "Cultural!", "Heritage!"],
    "square dance": ["Square dancing is American!", "Calls!", "Group!"],
    "polka": ["Polka is lively!", "European!", "Bouncy!"],
    "cha cha": ["Cha cha is Latin!", "Rhythm!", "Fun!"],
    "rumba": ["Rumba is romantic!", "Cuban!", "Slow!"],
    "samba": ["Samba is Brazilian!", "Carnival!", "Energetic!"],
    "merengue": ["Merengue is Dominican!", "Simple steps!", "Fun!"],
    "bachata": ["Bachata is romantic!", "Dominican!", "Partner!"],
    
    # Photography
    "camera": ["Cameras capture images!", "Photos!", "Memories!"],
    "lens": ["Lenses focus light!", "Optics!", "Zoom!"],
    "photo": ["Photos preserve moments!", "Images!", "Memories!"],
    "portrait": ["Portraits capture people!", "Face!", "Expression!"],
    "landscape": ["Landscapes capture scenery!", "Nature!", "Wide!"],
    "macro": ["Macro is close-up!", "Detail!", "Small subjects!"],
    "exposure": ["Exposure is light amount!", "Brightness!", "Settings!"],
    "aperture": ["Aperture controls light!", "F-stop!", "Depth!"],
    "shutter": ["Shutter controls time!", "Speed!", "Motion!"],
    "iso": ["ISO is light sensitivity!", "Grain!", "Low light!"],
    "focus": ["Focus is sharpness!", "Clear!", "Subject!"],
    "composition": ["Composition arranges elements!", "Rule of thirds!", "Framing!"],
    "editing": ["Editing improves photos!", "Post-processing!", "Software!"],
    "filter": ["Filters alter images!", "Effects!", "Style!"],
    "tripod": ["Tripods stabilize cameras!", "Steady!", "Long exposures!"],
    "flash": ["Flash adds light!", "Artificial!", "Dark situations!"],
    "selfie": ["Selfies are self-portraits!", "Front camera!", "Social media!"],
    
    # Communication
    "communication": ["Communication shares ideas!", "Talking!", "Understanding!"],
    "language": ["Language is words!", "Speech!", "Writing!"],
    "speech": ["Speech is vocal communication!", "Talking!", "Public!"],
    "conversation": ["Conversation is dialogue!", "Two-way!", "Chat!"],
    "discussion": ["Discussion exchanges ideas!", "Talk!", "Debate!"],
    "debate": ["Debate argues points!", "Formal!", "Opposing views!"],
    "presentation": ["Presentations share info!", "Slides!", "Public speaking!"],
    "meeting": ["Meetings gather people!", "Discussion!", "Work!"],
    "email": ["Email is digital mail!", "Communication!", "Work!"],
    "message": ["Messages are communications!", "Text!", "Quick!"],
    "text": ["Texting is quick messaging!", "Phone!", "SMS!"],
    "call": ["Calls are voice communication!", "Phone!", "Talking!"],
    "video call": ["Video calls show faces!", "Zoom!", "Remote!"],
    "letter": ["Letters are written messages!", "Mail!", "Personal!"],
    "note": ["Notes are brief messages!", "Reminders!", "Quick!"],
    "announcement": ["Announcements share news!", "Public!", "Important!"],
    "news": ["News reports events!", "Media!", "Information!"],
    "media": ["Media spreads information!", "TV, radio, internet!", "Communication!"],
    "broadcast": ["Broadcasting sends to many!", "TV, radio!", "Wide reach!"],
    "publish": ["Publishing shares work!", "Books, articles!", "Public!"],
    "interview": ["Interviews ask questions!", "Job!", "Media!"],
    "podcast": ["Podcasts are audio shows!", "Listen!", "Topics!"],
    "newsletter": ["Newsletters share updates!", "Email!", "Regular!"],
    "blog": ["Blogs share thoughts online!", "Writing!", "Internet!"],
    "article": ["Articles inform readers!", "News!", "Writing!"],
    "report": ["Reports document findings!", "Research!", "Business!"],
    "document": ["Documents record info!", "Papers!", "Digital!"],
    "manual": ["Manuals instruct!", "How-to!", "Guides!"],
    "guide": ["Guides help navigate!", "Instructions!", "Helpful!"],
    "tutorial": ["Tutorials teach steps!", "Learning!", "How-to!"],
    "instructions": ["Instructions direct action!", "Steps!", "Follow!"],
    "feedback": ["Feedback gives responses!", "Input!", "Improvement!"],
    "review": ["Reviews evaluate!", "Opinions!", "Ratings!"],
    "comment": ["Comments share thoughts!", "Response!", "Feedback!"],
    "opinion": ["Opinions are personal views!", "Subjective!", "Perspective!"],
    "fact": ["Facts are true statements!", "Verified!", "Objective!"],
    "rumor": ["Rumors are unverified!", "Gossip!", "Unconfirmed!"],
    "gossip": ["Gossip is casual talk!", "Rumors!", "Social!"],
    "secret": ["Secrets are hidden info!", "Private!", "Confidential!"],
    "truth": ["Truth is reality!", "Honest!", "Accurate!"],
    "lie": ["Lies are false statements!", "Deception!", "Dishonest!"],
    "joke": ["Jokes are humorous!", "Laughter!", "Fun!"],
    "story": ["Stories are narratives!", "Tales!", "Fiction or fact!"],
    "tale": ["Tales are stories!", "Narratives!", "Adventure!"],
    "myth": ["Myths are traditional stories!", "Legends!", "Cultural!"],
    "legend": ["Legends are famous stories!", "Heroes!", "Cultural!"],
}
