"""Nature, weather, animals, and environment responses"""

NATURE = {
    # Weather
    "weather": ["Weather is fascinating! What's it like there?", "I love weather talk!", "Any weather preferences?"],
    "rain": ["Rain is so calming!", "Rainy days are cozy!", "Do you enjoy the rain?"],
    "snow": ["Snow is magical!", "Winter wonderland!", "Do you like snow?"],
    "sunny": ["Sunny days are great!", "Sunshine brings happiness!", "Love the sun!"],
    "cloudy": ["Cloudy days can be cozy!", "Sometimes clouds are nice!", "Cloud watching!"],
    "storm": ["Storms can be intense!", "Stay safe in storms!", "Nature's power!"],
    "wind": ["Wind can be refreshing!", "Breezy days!", "Windy weather!"],
    "temperature": ["Temperature affects comfort!", "Hot or cold?", "Climate matters!"],
    "hot": ["Hot weather needs cooling!", "Summer vibes!", "Stay hydrated!"],
    "cold": ["Cold weather needs warmth!", "Cozy inside!", "Bundle up!"],
    "humid": ["Humidity is sticky!", "Tropical!", "Moisture in air!"],
    "dry": ["Dry weather cracks!", "Arid!", "Moisturize!"],
    "fog": ["Fog is mysterious!", "Low visibility!", "Atmospheric!"],
    "hurricane": ["Hurricanes are powerful!", "Stay safe!", "Storm surge!"],
    "tornado": ["Tornadoes are scary!", "Seek shelter!", "Powerful!"],
    "thunder": ["Thunder rumbles!", "Storms!", "Lightning follows!"],
    "lightning": ["Lightning is electric!", "Spectacular!", "Dangerous!"],
    "rainbow": ["Rainbows are beautiful!", "After rain!", "Colorful!"],
    "hail": ["Hail is ice falling!", "Dangerous!", "Storms!"],
    "blizzard": ["Blizzards are intense!", "Snow storms!", "Stay inside!"],
    "drought": ["Droughts lack rain!", "Water shortage!", "Dry conditions!"],
    "flood": ["Floods are dangerous!", "Too much water!", "Evacuate!"],
    "forecast": ["Forecasts predict weather!", "Planning!", "Meteorology!"],
    "climate": ["Climate is long-term patterns!", "Global!", "Change!"],
    "season": ["Seasons change throughout year!", "Cycles!", "Nature's rhythm!"],
    "spring": ["Spring brings new life!", "Flowers bloom!", "Renewal!"],
    "summer": ["Summer is warm!", "Vacation time!", "Beach days!"],
    "autumn": ["Autumn has beautiful colors!", "Fall foliage!", "Harvest!"],
    "fall": ["Fall leaves are gorgeous!", "Cooling down!", "Cozy!"],
    "winter": ["Winter is cold!", "Snow and holidays!", "Cozy indoors!"],
    
    # Animals
    "animal": ["Animals are amazing!", "What's your favorite?", "Nature's creatures!"],
    "dog": ["Dogs are loyal friends!", "Man's best friend!", "Woof!"],
    "cat": ["Cats are independent!", "Purring companions!", "Meow!"],
    "bird": ["Birds can fly!", "Singing!", "Beautiful!"],
    "fish": ["Fish live in water!", "Aquariums are relaxing!", "Swimming!"],
    "horse": ["Horses are majestic!", "Riding!", "Powerful!"],
    "cow": ["Cows give milk!", "Farm animals!", "Moo!"],
    "pig": ["Pigs are smart!", "Farm animals!", "Oink!"],
    "sheep": ["Sheep give wool!", "Baaa!", "Fluffy!"],
    "chicken": ["Chickens lay eggs!", "Farm birds!", "Cluck!"],
    "duck": ["Ducks swim and fly!", "Quack!", "Waterfowl!"],
    "rabbit": ["Rabbits are cute!", "Hoppy!", "Soft fur!"],
    "hamster": ["Hamsters are small and cute!", "Running wheels!", "Pets!"],
    "turtle": ["Turtles are slow!", "Shells!", "Long-lived!"],
    "snake": ["Snakes slither!", "Reptiles!", "Some are venomous!"],
    "lizard": ["Lizards are reptiles!", "Scaly!", "Cold-blooded!"],
    "frog": ["Frogs hop and croak!", "Amphibians!", "Ribbit!"],
    "lion": ["Lions are kings!", "Roar!", "African!"],
    "tiger": ["Tigers are powerful!", "Striped!", "Endangered!"],
    "elephant": ["Elephants are intelligent!", "Large!", "Never forget!"],
    "giraffe": ["Giraffes are tall!", "Long necks!", "African!"],
    "zebra": ["Zebras have stripes!", "African!", "Unique patterns!"],
    "monkey": ["Monkeys are playful!", "Primates!", "Smart!"],
    "bear": ["Bears are strong!", "Furry!", "Hibernation!"],
    "wolf": ["Wolves are pack animals!", "Howling!", "Wild!"],
    "fox": ["Foxes are clever!", "Red fur!", "Cunning!"],
    "deer": ["Deer are graceful!", "Antlers!", "Forest dwellers!"],
    "whale": ["Whales are massive!", "Ocean giants!", "Singing!"],
    "dolphin": ["Dolphins are intelligent!", "Playful!", "Ocean acrobats!"],
    "shark": ["Sharks are apex predators!", "Ocean!", "Fascinating!"],
    "octopus": ["Octopi are smart!", "Eight arms!", "Clever!"],
    "penguin": ["Penguins are adorable!", "Waddling!", "Cold climates!"],
    "owl": ["Owls are wise!", "Night hunters!", "Hoot!"],
    "eagle": ["Eagles are majestic!", "Soaring!", "Powerful!"],
    "parrot": ["Parrots can talk!", "Colorful!", "Tropical!"],
    "butterfly": ["Butterflies are beautiful!", "Transformation!", "Delicate!"],
    "bee": ["Bees make honey!", "Buzzing!", "Essential pollinators!"],
    "spider": ["Spiders spin webs!", "Eight legs!", "Arachnids!"],
    "ant": ["Ants are hardworking!", "Colonies!", "Strong!"],
    "mosquito": ["Mosquitoes are annoying!", "Biting!", "Summer pests!"],
    
    # Marine Life
    "ocean": ["Oceans cover most of Earth!", "Marine life!", "Deep blue!"],
    "sea": ["The sea is vast!", "Salty water!", "Mysteries!"],
    "coral": ["Coral reefs are diverse!", "Colorful!", "Endangered!"],
    "jellyfish": ["Jellyfish are fascinating!", "Stinging!", "Translucent!"],
    "starfish": ["Starfish have five arms!", "Regeneration!", "Ocean floor!"],
    "crab": ["Crabs walk sideways!", "Claws!", "Crustaceans!"],
    "lobster": ["Lobsters are delicacies!", "Claws!", "Ocean floor!"],
    "shrimp": ["Shrimp are small crustaceans!", "Seafood!", "Tasty!"],
    "clam": ["Clams have shells!", "Bivalves!", "Pearls!"],
    "oyster": ["Oysters make pearls!", "Shellfish!", "Delicacy!"],
    "mussel": ["Mussels attach to rocks!", "Shellfish!", "Coastal!"],
    "squid": ["Squid have tentacles!", "Ink!", "Deep sea!"],
    "seahorse": ["Seahorses are unique!", "Males carry babies!", "Cute!"],
    "stingray": ["Stingrays glide!", "Flat!", "Barbed tail!"],
    "eel": ["Eels are long fish!", "Electric!", "Slippery!"],
    "tuna": ["Tuna are fast swimmers!", "Popular fish!", "Sushi!"],
    "salmon": ["Salmon swim upstream!", "Spawning!", "Nutritious!"],
    "cod": ["Cod is popular fish!", "Atlantic!", "Fish and chips!"],
    "trout": ["Trout live in streams!", "Freshwater!", "Fishing!"],
    "bass": ["Bass are sport fish!", "Freshwater!", "Fishing!"],
    "swordfish": ["Swordfish have long bills!", "Fast!", "Deep sea!"],
    "marlin": ["Marlins are game fish!", "Billfish!", "Fishing!"],
    "manta ray": ["Manta rays are huge!", "Graceful!", "Ocean!"],
    "orca": ["Orcas are killer whales!", "Intelligent!", "Pods!"],
    "manatee": ["Manatees are gentle!", "Sea cows!", "Herbivores!"],
    "seal": ["Seals are playful!", "Pinnipeds!", "Beaches!"],
    "walrus": ["Walruses have tusks!", "Arctic!", "Large!"],
    "sea turtle": ["Sea turtles migrate!", "Ancient!", "Conservation!"],
    "sea lion": ["Sea lions bark!", "Coastal!", "Playful!"],
    "otter": ["Otters are adorable!", "Playful!", "Hold hands!"],
    
    # Insects
    "insect": ["Insects are diverse!", "Six legs!", "Everywhere!"],
    "beetle": ["Beetles are diverse!", "Hard shells!", "Many species!"],
    "ladybug": ["Ladybugs are good luck!", "Red with spots!", "Garden helpers!"],
    "dragonfly": ["Dragonflies fly fast!", "Beautiful!", "Near water!"],
    "grasshopper": ["Grasshoppers jump far!", "Chirping!", "Green!"],
    "cricket": ["Crickets chirp at night!", "Jumping!", "Sounds of summer!"],
    "firefly": ["Fireflies glow!", "Magical!", "Summer nights!"],
    "moth": ["Moths like light!", "Night butterflies!", "Fuzzy!"],
    "caterpillar": ["Caterpillars become butterflies!", "Munching!", "Transformation!"],
    "centipede": ["Centipedes have many legs!", "Fast!", "Not insects actually!"],
    "millipede": ["Millipedes curl up!", "Many legs!", "Slow!"],
    "wasp": ["Wasps can sting!", "Yellow and black!", "Aggressive!"],
    "hornet": ["Hornets are large wasps!", "Dangerous!", "Nests!"],
    "fly": ["Flies are annoying!", "Buzzing!", "Quick!"],
    "termite": ["Termites eat wood!", "Colonies!", "Destructive!"],
    "cockroach": ["Cockroaches are hardy!", "Survive anything!", "Pests!"],
    "flea": ["Fleas bite!", "Tiny!", "Pets beware!"],
    "tick": ["Ticks attach!", "Disease carriers!", "Check yourself!"],
    "lice": ["Lice are parasites!", "Itchy!", "Contagious!"],
    "bed bug": ["Bed bugs bite at night!", "Pests!", "Hard to eliminate!"],
    "praying mantis": ["Praying mantises are hunters!", "Ambush predators!", "Cool!"],
    "scorpion": ["Scorpions have stingers!", "Desert!", "Arachnids!"],
    
    # Trees & Plants
    "tree": ["Trees give us oxygen!", "Forests!", "Nature!"],
    "flower": ["Flowers are beautiful!", "Blooming!", "Colorful!"],
    "plant": ["Plants are essential!", "Photosynthesis!", "Green!"],
    "grass": ["Grass covers lawns!", "Green!", "Mowing!"],
    "forest": ["Forests are ecosystems!", "Trees!", "Wildlife!"],
    "jungle": ["Jungles are dense!", "Tropical!", "Diverse!"],
    "garden": ["Gardens are peaceful!", "Growing!", "Beautiful!"],
    "rose": ["Roses are romantic!", "Beautiful flowers!", "Fragrant!"],
    "tulip": ["Tulips are spring flowers!", "Colorful!", "Dutch!"],
    "sunflower": ["Sunflowers follow the sun!", "Yellow!", "Cheerful!"],
    "daisy": ["Daisies are simple and pretty!", "White petals!", "Cheerful!"],
    "lily": ["Lilies are elegant!", "Fragrant!", "Beautiful!"],
    "orchid": ["Orchids are exotic!", "Delicate!", "Beautiful!"],
    "cactus": ["Cacti survive deserts!", "Spiny!", "Water storage!"],
    "succulent": ["Succulents are trendy!", "Easy care!", "Water storing!"],
    "fern": ["Ferns are ancient plants!", "Fronds!", "Shade lovers!"],
    "moss": ["Moss is soft!", "Green carpet!", "Moist areas!"],
    "vine": ["Vines climb!", "Grapes!", "Trailing!"],
    "oak": ["Oak trees are strong!", "Acorns!", "Long-lived!"],
    "maple": ["Maple trees have beautiful leaves!", "Syrup!", "Fall colors!"],
    "pine": ["Pine trees are evergreen!", "Needles!", "Cones!"],
    "birch": ["Birch trees have white bark!", "Elegant!", "Northern!"],
    "willow": ["Willows have hanging branches!", "Weeping!", "Near water!"],
    "palm": ["Palm trees are tropical!", "Coconuts!", "Beach vibes!"],
    "bamboo": ["Bamboo grows fast!", "Strong!", "Pandas eat it!"],
    "redwood": ["Redwoods are massive!", "Tallest trees!", "Ancient!"],
    "sequoia": ["Sequoias are giant!", "California!", "Oldest trees!"],
    "bonsai": ["Bonsai are miniature trees!", "Japanese art!", "Patience!"],
    "herb": ["Herbs flavor food!", "Fresh!", "Gardens!"],
    "shrub": ["Shrubs are bushes!", "Landscaping!", "Hedges!"],
    "bush": ["Bushes provide cover!", "Landscaping!", "Wildlife habitat!"],
    "weed": ["Weeds are unwanted plants!", "Persistent!", "Gardening challenge!"],
    "seed": ["Seeds grow plants!", "Germination!", "Beginning of life!"],
    "root": ["Roots anchor plants!", "Underground!", "Nutrient absorption!"],
    "leaf": ["Leaves photosynthesize!", "Green!", "Oxygen producers!"],
    "branch": ["Branches support leaves!", "Tree structure!", "Birds perch!"],
    "trunk": ["Trunks support trees!", "Strong!", "Wood source!"],
    "bark": ["Bark protects trees!", "Outer layer!", "Texture!"],
    "pollen": ["Pollen fertilizes plants!", "Allergies!", "Bees spread it!"],
    "nectar": ["Nectar feeds pollinators!", "Sweet!", "Flowers produce it!"],
}
