"""Science, space, and natural world responses"""

SCIENCE = {
    # Space & Astronomy
    "space": ["Space is infinite!", "The final frontier!", "So many mysteries!"],
    "planet": ["Planets are fascinating!", "Our solar system!", "Worlds beyond!"],
    "star": ["Stars light up the sky!", "Nuclear fusion!", "Distant suns!"],
    "moon": ["The moon affects our tides!", "Our natural satellite!", "Lunar beauty!"],
    "sun": ["The sun gives us life!", "Our star!", "Energy source!"],
    "galaxy": ["Galaxies contain billions of stars!", "Milky Way!", "Cosmic scale!"],
    "universe": ["The universe is vast!", "Everything that exists!", "Mind-boggling!"],
    "nasa": ["NASA explores space!", "Space missions!", "Science!"],
    "rocket": ["Rockets reach space!", "Propulsion!", "Launch!"],
    "satellite": ["Satellites orbit Earth!", "Communication!", "GPS!"],
    "astronaut": ["Astronauts explore space!", "Space travelers!", "Heroes!"],
    "mars": ["Mars is the red planet!", "Exploration!", "Future colony?"],
    "jupiter": ["Jupiter is massive!", "Gas giant!", "Great Red Spot!"],
    "saturn": ["Saturn has rings!", "Beautiful planet!", "Gas giant!"],
    "venus": ["Venus is hot!", "Morning star!", "Earth's twin!"],
    "mercury": ["Mercury is closest to sun!", "Small planet!", "Hot and cold!"],
    "neptune": ["Neptune is far!", "Blue planet!", "Ice giant!"],
    "uranus": ["Uranus rotates sideways!", "Ice giant!", "Unique!"],
    "pluto": ["Pluto is a dwarf planet!", "Still loved!", "Kuiper belt!"],
    "asteroid": ["Asteroids are space rocks!", "Belt!", "Potential threat!"],
    "comet": ["Comets have tails!", "Ice and dust!", "Spectacular!"],
    "meteor": ["Meteors streak across sky!", "Shooting stars!", "Space debris!"],
    "black hole": ["Black holes bend space!", "Gravity!", "Mysterious!"],
    "nebula": ["Nebulae are star nurseries!", "Colorful!", "Gas clouds!"],
    "constellation": ["Constellations form patterns!", "Star groups!", "Navigation!"],
    "telescope": ["Telescopes see far!", "Astronomy!", "Observation!"],
    "hubble": ["Hubble sees deep space!", "Space telescope!", "Amazing images!"],
    "james webb": ["James Webb is new!", "Infrared!", "Discovery!"],
    "milky way": ["Milky Way is our home!", "Galaxy!", "Billions of stars!"],
    "orbit": ["Orbits are paths!", "Around objects!", "Gravity!"],
    "gravity": ["Gravity attracts mass!", "Fundamental force!", "Einstein!"],
    "light year": ["Light years measure distance!", "Space scale!", "Vast!"],
    "alien": ["Aliens might exist!", "Extraterrestrial!", "Unknown!"],
    "ufo": ["UFOs are unidentified!", "Mystery!", "Sightings!"],
    "spacex": ["SpaceX innovates!", "Private space!", "Elon Musk!"],
    
    # Physics & Chemistry
    "atom": ["Atoms are tiny!", "Building blocks!", "Matter!"],
    "molecule": ["Molecules combine atoms!", "Chemistry!", "Bonds!"],
    "electron": ["Electrons orbit nuclei!", "Negative charge!", "Tiny!"],
    "proton": ["Protons are positive!", "In nucleus!", "Atomic number!"],
    "neutron": ["Neutrons are neutral!", "In nucleus!", "Isotopes!"],
    "element": ["Elements are fundamental!", "Periodic table!", "Building blocks!"],
    "periodic table": ["Periodic table organizes elements!", "Chemistry!", "Patterns!"],
    "chemical": ["Chemicals react!", "Substances!", "Science!"],
    "reaction": ["Reactions change matter!", "Chemistry!", "Energy!"],
    "energy": ["Energy powers everything!", "Cannot be created or destroyed!", "Fundamental!"],
    "matter": ["Matter has mass!", "Everything physical!", "Atoms!"],
    "force": ["Forces cause motion!", "Physics!", "Interaction!"],
    "motion": ["Motion is movement!", "Physics!", "Velocity!"],
    "velocity": ["Velocity is speed with direction!", "Physics!", "Motion!"],
    "acceleration": ["Acceleration changes velocity!", "Physics!", "Force!"],
    "momentum": ["Momentum is mass times velocity!", "Physics!", "Conservation!"],
    "friction": ["Friction opposes motion!", "Physics!", "Heat!"],
    "electricity": ["Electricity powers our world!", "Electrons!", "Energy!"],
    "magnetism": ["Magnetism attracts and repels!", "Physics!", "Fields!"],
    "radiation": ["Radiation is energy!", "Can be harmful!", "Waves!"],
    "nuclear": ["Nuclear is atomic!", "Energy or weapons!", "Powerful!"],
    "quantum": ["Quantum is tiny scale!", "Physics!", "Strange!"],
    "relativity": ["Relativity is Einstein!", "Space and time!", "Revolutionary!"],
    "thermodynamics": ["Thermodynamics studies heat!", "Laws!", "Energy!"],
    "optics": ["Optics studies light!", "Lenses!", "Vision!"],
    "wave": ["Waves transfer energy!", "Physics!", "Patterns!"],
    "frequency": ["Frequency is rate!", "Waves!", "Hertz!"],
    "wavelength": ["Wavelength is distance!", "Waves!", "Color!"],
    
    # Biology & Life Science
    "cell": ["Cells are life's building blocks!", "Biology!", "Organisms!"],
    "dna": ["DNA carries genetic info!", "Double helix!", "Life's code!"],
    "gene": ["Genes determine traits!", "Heredity!", "DNA segments!"],
    "evolution": ["Evolution changes species!", "Natural selection!", "Darwin!"],
    "species": ["Species are life forms!", "Classification!", "Diversity!"],
    "organism": ["Organisms are living things!", "Biology!", "Life!"],
    "bacteria": ["Bacteria are single-celled!", "Microscopic!", "Everywhere!"],
    "virus": ["Viruses infect cells!", "Tiny!", "Disease!"],
    "protein": ["Proteins do cell work!", "Biology!", "Amino acids!"],
    "enzyme": ["Enzymes speed reactions!", "Biology!", "Catalysts!"],
    "photosynthesis": ["Photosynthesis makes food!", "Plants!", "Sunlight!"],
    "respiration": ["Respiration releases energy!", "Breathing!", "Cells!"],
    "ecosystem": ["Ecosystems are communities!", "Nature!", "Balance!"],
    "biodiversity": ["Biodiversity is variety!", "Species!", "Health!"],
    "extinction": ["Extinction is forever!", "Species loss!", "Conservation!"],
    "fossil": ["Fossils preserve history!", "Ancient life!", "Evidence!"],
    "dinosaur": ["Dinosaurs ruled once!", "Extinct!", "Fascinating!"],
    "mammal": ["Mammals nurse young!", "Warm-blooded!", "Includes us!"],
    "reptile": ["Reptiles are cold-blooded!", "Scales!", "Lizards and snakes!"],
    "amphibian": ["Amphibians live both ways!", "Water and land!", "Frogs!"],
    "bird": ["Birds have feathers!", "Flight!", "Evolved from dinosaurs!"],
    "insect": ["Insects have six legs!", "Arthropods!", "Most diverse!"],
    "microbe": ["Microbes are tiny!", "Bacteria and more!", "Microscopic!"],
    "anatomy": ["Anatomy studies body structure!", "Medicine!", "Biology!"],
    "physiology": ["Physiology studies function!", "Body systems!", "Biology!"],
    "neuroscience": ["Neuroscience studies brain!", "Mind!", "Neurons!"],
    "genetics": ["Genetics studies heredity!", "DNA!", "Traits!"],
    "ecology": ["Ecology studies ecosystems!", "Environment!", "Relationships!"],
    "botany": ["Botany studies plants!", "Flora!", "Green!"],
    "zoology": ["Zoology studies animals!", "Fauna!", "Creatures!"],
    "microbiology": ["Microbiology studies microbes!", "Tiny life!", "Lab!"],
    
    # Geology & Earth Science
    "geology": ["Geology studies Earth!", "Rocks!", "History!"],
    "rock": ["Rocks form Earth's crust!", "Minerals!", "Types!"],
    "mineral": ["Minerals are natural solids!", "Crystals!", "Chemistry!"],
    "volcano": ["Volcanoes erupt!", "Magma!", "Powerful!"],
    "earthquake": ["Earthquakes shake ground!", "Tectonic!", "Dangerous!"],
    "tectonic": ["Tectonics moves plates!", "Geology!", "Earthquakes!"],
    "plate": ["Plates make up crust!", "Moving!", "Continents!"],
    "continent": ["Continents are land masses!", "Seven!", "Geography!"],
    "ocean": ["Oceans cover Earth!", "Water!", "Life!"],
    "atmosphere": ["Atmosphere surrounds Earth!", "Air!", "Protection!"],
    "climate": ["Climate is long-term weather!", "Patterns!", "Change!"],
    "erosion": ["Erosion wears away!", "Water and wind!", "Landscape!"],
    "sediment": ["Sediment settles!", "Layers!", "History!"],
    "crystal": ["Crystals have structure!", "Minerals!", "Beautiful!"],
    "gem": ["Gems are precious!", "Beautiful!", "Valuable!"],
    "diamond": ["Diamonds are hard!", "Carbon!", "Precious!"],
    "gold": ["Gold is precious metal!", "Valuable!", "Soft!"],
    "silver": ["Silver is precious!", "Conductive!", "Beautiful!"],
    "copper": ["Copper conducts!", "Metal!", "Wiring!"],
    "iron": ["Iron is strong!", "Metal!", "Steel!"],
    
    # Environmental Science
    "environment": ["The environment is everything around us!", "Nature!", "Protect it!"],
    "pollution": ["Pollution harms environment!", "Clean up!", "Prevention!"],
    "recycling": ["Recycling saves resources!", "Reduce, reuse, recycle!", "Sustainability!"],
    "sustainability": ["Sustainability preserves future!", "Balance!", "Long-term!"],
    "renewable": ["Renewable energy regenerates!", "Solar, wind!", "Future!"],
    "solar": ["Solar power uses sun!", "Clean energy!", "Panels!"],
    "wind": ["Wind power is clean!", "Turbines!", "Renewable!"],
    "conservation": ["Conservation protects nature!", "Preservation!", "Wildlife!"],
    "deforestation": ["Deforestation destroys forests!", "Trees cut!", "Problem!"],
    "carbon": ["Carbon is essential element!", "Life!", "Climate!"],
    "greenhouse": ["Greenhouse effect warms Earth!", "Climate!", "Gases!"],
    "ozone": ["Ozone protects us!", "UV shield!", "Atmosphere!"],
    "biodegradable": ["Biodegradable breaks down!", "Natural!", "Eco-friendly!"],
    "compost": ["Composting recycles organic!", "Garden!", "Nutrients!"],
    "ecosystem": ["Ecosystems are interconnected!", "Balance!", "Nature!"],
    "habitat": ["Habitats are homes!", "Species!", "Environment!"],
    "endangered": ["Endangered species need help!", "Conservation!", "Protection!"],
    "wildlife": ["Wildlife is wild animals!", "Nature!", "Diversity!"],
    "marine": ["Marine is ocean!", "Sea life!", "Underwater!"],
    "coral": ["Coral reefs are diverse!", "Ocean!", "Colorful!"],
    "rainforest": ["Rainforests are biodiverse!", "Tropical!", "Lungs of Earth!"],
}
