"""Sports, fitness, and athletics responses"""

SPORTS = {
    # Sports & Fitness
    "sport": ["Sports are exciting! Which do you follow?", "Athletics keep us healthy!", "Team sports or individual?"],
    "sports": ["Sports bring people together!", "What's your favorite sport?", "Do you play or watch?"],
    "football": ["Football is intense! NFL or college?", "Touchdown!", "What's your favorite team?"],
    "soccer": ["Soccer is the world's sport!", "Goal!", "Which league do you follow?"],
    "basketball": ["Basketball is fast-paced!", "Slam dunk!", "NBA fan?"],
    "baseball": ["Baseball is America's pastime!", "Home run!", "Which team do you root for?"],
    "hockey": ["Hockey is intense!", "Hat trick!", "NHL or other leagues?"],
    "tennis": ["Tennis is elegant!", "Love-all!", "Singles or doubles?"],
    "golf": ["Golf is relaxing!", "Fore!", "What's your handicap?"],
    "running": ["Running is great exercise!", "Marathon goals?", "Track or trails?"],
    "swimming": ["Swimming is full-body exercise!", "Pool or ocean?", "Great cardio!"],
    "gym": ["The gym is a great habit!", "Weights or cardio?", "Fitness journey!"],
    "exercise": ["Exercise is so important!", "What's your routine?", "Stay active!"],
    "workout": ["Workouts keep us fit!", "What's your routine?", "Feeling strong!"],
    "fitness": ["Fitness is a lifestyle!", "Health is wealth!", "What's your routine?"],
    "yoga": ["Yoga is calming!", "Namaste!", "Mind and body connection!"],
    "cycling": ["Cycling is great!", "Bike rides are fun!", "Road or mountain?"],
    
    # Sports Equipment
    "ball": ["Balls are sports essentials!", "Many sports use them!", "Spherical fun!"],
    "racket": ["Rackets hit hard!", "Tennis, badminton!", "Swing!"],
    "bat": ["Bats hit baseballs!", "Wooden or metal!", "Crack!"],
    "glove": ["Gloves protect hands!", "Baseball, boxing!", "Catch!"],
    "helmet": ["Helmets protect heads!", "Safety first!", "Essential gear!"],
    "skates": ["Skates glide!", "Ice or roller!", "Smooth!"],
    "skis": ["Skis ride snow!", "Downhill!", "Mountains!"],
    "snowboard": ["Snowboards shred!", "Winter sport!", "Mountains!"],
    "surfboard": ["Surfboards ride waves!", "Ocean sport!", "Hang ten!"],
    "wetsuit": ["Wetsuits keep warm!", "Water sports!", "Neoprene!"],
    "goggles": ["Goggles protect eyes!", "Swimming, skiing!", "Vision!"],
    "cleats": ["Cleats grip turf!", "Soccer, football!", "Traction!"],
    "pads": ["Pads protect body!", "Football, hockey!", "Safety!"],
    "weights": ["Weights build muscle!", "Gym equipment!", "Lift!"],
    "dumbbell": ["Dumbbells are versatile!", "Free weights!", "Strength training!"],
    "barbell": ["Barbells are heavy!", "Squats, bench!", "Compound lifts!"],
    "treadmill": ["Treadmills run indoors!", "Cardio machine!", "Run!"],
    "elliptical": ["Ellipticals are low impact!", "Cardio!", "Smooth motion!"],
    "bike": ["Bikes ride!", "Stationary or road!", "Pedal!"],
    "mat": ["Mats cushion!", "Yoga, gymnastics!", "Comfort!"],
    "net": ["Nets catch!", "Tennis, volleyball!", "Score!"],
    "hoop": ["Hoops score!", "Basketball!", "Swish!"],
    "goal": ["Goals are targets!", "Soccer, hockey!", "Score!"],
    "club": ["Clubs hit golf balls!", "Drivers, putters!", "Swing!"],
    "putter": ["Putters are for short shots!", "Golf!", "Tap in!"],
    "driver": ["Drivers hit far!", "Golf!", "Tee shot!"],
    
    # More Sports
    "volleyball": ["Volleyball is fun!", "Beach or indoor!", "Spike it!"],
    "badminton": ["Badminton is quick!", "Shuttlecock!", "Fast reflexes!"],
    "ping pong": ["Ping pong is fast!", "Table tennis!", "Quick!"],
    "boxing": ["Boxing is intense!", "Knockout!", "Training!"],
    "mma": ["MMA combines styles!", "UFC!", "Mixed martial arts!"],
    "wrestling": ["Wrestling is grappling!", "Olympic sport!", "Pin!"],
    "gymnastics": ["Gymnastics is impressive!", "Flexibility!", "Olympics!"],
    "skiing": ["Skiing is thrilling!", "Slopes!", "Powder!"],
    "snowboarding": ["Snowboarding is cool!", "Mountains!", "Tricks!"],
    "surfing": ["Surfing is awesome!", "Waves!", "Beach culture!"],
    "skateboarding": ["Skateboarding is rad!", "Tricks!", "Street culture!"],
    "climbing": ["Climbing is challenging!", "Rock walls!", "Heights!"],
    "hiking": ["Hiking connects with nature!", "Trails!", "Fresh air!"],
    "marathon": ["Marathons test endurance!", "26.2 miles!", "Runners!"],
    "triathlon": ["Triathlons combine sports!", "Swim, bike, run!", "Endurance!"],
    "cricket": ["Cricket is popular!", "Bat and ball!", "International!"],
    "rugby": ["Rugby is tough!", "No pads!", "Scrum!"],
    "lacrosse": ["Lacrosse is fast!", "Sticks!", "Native American origin!"],
    "archery": ["Archery takes focus!", "Bow and arrow!", "Aim!"],
    "fencing": ["Fencing is elegant!", "Swords!", "En garde!"],
    "rowing": ["Rowing is team sport!", "Water!", "Stroke!"],
    "sailing": ["Sailing is peaceful!", "Wind power!", "Ocean!"],
    "diving": ["Diving is graceful!", "Springboard!", "Splash!"],
    "figure skating": ["Figure skating is artistic!", "Ice!", "Jumps!"],
    "curling": ["Curling is unique!", "Ice!", "Sweeping!"],
    "bobsled": ["Bobsled is fast!", "Winter Olympics!", "Ice track!"],
    
    # Martial Arts
    "karate": ["Karate is discipline!", "Japanese!", "Strikes!"],
    "judo": ["Judo uses throws!", "Japanese!", "Olympic sport!"],
    "taekwondo": ["Taekwondo is kicking!", "Korean!", "Olympic sport!"],
    "jiujitsu": ["Jiu-jitsu is grappling!", "Brazilian!", "Ground game!"],
    "kungfu": ["Kung fu is diverse!", "Chinese!", "Many styles!"],
    "aikido": ["Aikido redirects force!", "Japanese!", "Defensive!"],
    "kendo": ["Kendo uses bamboo swords!", "Japanese!", "Way of the sword!"],
    "muay thai": ["Muay Thai is Thai boxing!", "8 limbs!", "Striking!"],
    "kickboxing": ["Kickboxing combines punches and kicks!", "Cardio!", "Fitness!"],
    "capoeira": ["Capoeira is dance-fight!", "Brazilian!", "Acrobatic!"],
    "sambo": ["Sambo is Russian grappling!", "Military!", "Throwing!"],
    "wing chun": ["Wing Chun is close combat!", "Chinese!", "Bruce Lee!"],
    "krav maga": ["Krav Maga is self-defense!", "Israeli!", "Practical!"],
    "hapkido": ["Hapkido is Korean martial art!", "Self-defense!", "Joint locks!"],
    "silat": ["Silat is Southeast Asian!", "Indonesian!", "Traditional!"],
    "sumo": ["Sumo is Japanese wrestling!", "Heavyweights!", "Traditional!"],
    
    # Outdoor Activities
    "camping": ["Camping connects with nature!", "Outdoors!", "Tents!"],
    "fishing": ["Fishing is relaxing!", "Catch of the day!", "Patience!"],
    "hunting": ["Hunting is traditional!", "Outdoor sport!", "Wildlife!"],
    "kayaking": ["Kayaking is paddling!", "Water sport!", "Adventure!"],
    "canoeing": ["Canoeing is classic!", "Paddling!", "Lakes and rivers!"],
    "rafting": ["Rafting is exciting!", "White water!", "Adventure!"],
    "snorkeling": ["Snorkeling sees underwater!", "Tropical!", "Fish!"],
    "scuba": ["Scuba dives deep!", "Underwater!", "Exploration!"],
    "parasailing": ["Parasailing flies high!", "Ocean views!", "Adventure!"],
    "zipline": ["Ziplining is thrilling!", "Heights!", "Speed!"],
    "bungee": ["Bungee jumping is extreme!", "Falling!", "Adrenaline!"],
    "skydiving": ["Skydiving is extreme!", "Freefall!", "Adrenaline rush!"],
    "paragliding": ["Paragliding soars!", "Wind!", "Views!"],
    "rock climbing": ["Rock climbing is challenging!", "Heights!", "Bouldering!"],
    "mountaineering": ["Mountaineering conquers peaks!", "Altitude!", "Adventure!"],
    "caving": ["Caving explores underground!", "Spelunking!", "Dark!"],
    "orienteering": ["Orienteering uses maps!", "Navigation!", "Wilderness!"],
    "geocaching": ["Geocaching is treasure hunting!", "GPS!", "Outdoor!"],
    "disc golf": ["Disc golf throws frisbees!", "Courses!", "Fun!"],
    "horseback riding": ["Horseback riding is classic!", "Equestrian!", "Animals!"],
    "trail running": ["Trail running is off-road!", "Nature!", "Endurance!"],
    "paddleboarding": ["Paddleboarding balances!", "Stand up!", "Water!"],
    "wakeboarding": ["Wakeboarding is towed!", "Boat!", "Tricks!"],
    "waterskiing": ["Water skiing is classic!", "Boat!", "Speed!"],
    "kiteboarding": ["Kiteboarding uses wind!", "Ocean!", "Extreme!"],
    "windsurfing": ["Windsurfing combines sailing and surfing!", "Wind!", "Ocean!"],
}
