"""Technology, computers, and digital responses"""

TECHNOLOGY = {
    # Technology
    "computer": ["Computers are amazing! What kind do you use?", "Technology is fascinating!", "PC or Mac?"],
    "phone": ["Phones are essential! iPhone or Android?", "Smartphones do everything!", "What's your favorite app?"],
    "internet": ["The internet changed everything!", "What do you use the internet for most?", "Information at our fingertips!"],
    "technology": ["Technology is advancing so fast!", "Tech is amazing!", "What tech do you find most interesting?"],
    "software": ["Software runs our world!", "What software do you use?", "Apps are everywhere!"],
    "hardware": ["Hardware is the backbone!", "Physical tech!", "Computers and devices!"],
    "app": ["Apps make life easier!", "Favorite apps?", "There's an app for that!"],
    "website": ["Websites are information hubs!", "What sites do you visit?", "The web is vast!"],
    "programming": ["Programming is creative!", "Code creates possibilities!", "What languages interest you?"],
    "coding": ["Coding is powerful!", "Building the future!", "It's problem-solving!"],
    "ai": ["AI is fascinating!", "The future is AI!", "Artificial intelligence is growing!"],
    "robot": ["Robots are cool!", "Automation is growing!", "The future is robotic!"],
    "laptop": ["Laptops are portable!", "Work anywhere!", "Convenience!"],
    "tablet": ["Tablets are versatile!", "Between phone and laptop!", "Touchscreen!"],
    "smartwatch": ["Smartwatches are handy!", "Wearable tech!", "Fitness tracking!"],
    "gadget": ["Gadgets are fun!", "Tech toys!", "Innovation!"],
    "update": ["Updates improve things!", "Keep current!", "New features!"],
    "download": ["Downloads bring content to you!", "Get files!", "Digital transfer!"],
    "upload": ["Uploads share content!", "Cloud storage!", "Sharing!"],
    "cloud": ["The cloud stores everything!", "Remote storage!", "Accessible anywhere!"],
    "data": ["Data is valuable!", "Information!", "Digital gold!"],
    "privacy": ["Privacy is important!", "Protect your data!", "Digital safety!"],
    "security": ["Security is essential!", "Stay safe online!", "Protection!"],
    "password": ["Passwords protect you!", "Strong passwords!", "Security!"],
    "hacker": ["Hackers can be good or bad!", "Cybersecurity!", "Digital skills!"],
    "virus": ["Computer viruses are bad!", "Antivirus!", "Stay protected!"],
    "wifi": ["WiFi connects us!", "Wireless internet!", "Connectivity!"],
    "bluetooth": ["Bluetooth is convenient!", "Wireless!", "Connection!"],
    "network": ["Networks connect devices!", "Internet!", "Communication!"],
    "server": ["Servers power the internet!", "Backend!", "Data centers!"],
    "database": ["Databases store information!", "Organized data!", "SQL!"],
    "algorithm": ["Algorithms solve problems!", "Code logic!", "Efficiency!"],
    "startup": ["Startups innovate!", "New businesses!", "Entrepreneurs!"],
    "tech": ["Tech is everywhere!", "Technology!", "Digital world!"],
    "digital": ["Digital is the future!", "Technology!", "Online world!"],
    "virtual": ["Virtual reality is cool!", "VR!", "Immersive!"],
    "vr": ["VR is immersive!", "Virtual reality!", "Gaming and more!"],
    "ar": ["AR enhances reality!", "Augmented reality!", "Cool tech!"],
    "drone": ["Drones fly and film!", "Aerial views!", "Technology!"],
    "electric": ["Electric vehicles are the future!", "Clean energy!", "EVs!"],
    "battery": ["Batteries power devices!", "Rechargeable!", "Energy storage!"],
    "charger": ["Chargers keep us powered!", "Plug in!", "Essential!"],
    "screen": ["Screens display content!", "Monitors!", "Visual!"],
    "monitor": ["Monitors are displays!", "Work setup!", "Visual!"],
    "keyboard": ["Keyboards input text!", "Typing!", "Essential!"],
    "mouse": ["Mice control cursors!", "Clicking!", "Navigation!"],
    "speaker": ["Speakers output sound!", "Audio!", "Music!"],
    "headphone": ["Headphones are personal audio!", "Listening!", "Portable!"],
    "microphone": ["Microphones capture sound!", "Recording!", "Podcasts!"],
    "camera": ["Cameras capture moments!", "Photography!", "Memories!"],
    "printer": ["Printers output documents!", "Paper!", "Office!"],
    "scanner": ["Scanners digitize documents!", "Paperless!", "Digital!"],
    "usb": ["USB connects devices!", "Universal!", "Data transfer!"],
    "hdmi": ["HDMI carries video!", "High definition!", "Display!"],
    "ssd": ["SSDs are fast storage!", "Solid state!", "Speed!"],
    "ram": ["RAM is memory!", "Speed!", "Multitasking!"],
    "processor": ["Processors are brains!", "CPU!", "Computing power!"],
    "gpu": ["GPUs handle graphics!", "Gaming!", "Rendering!"],
    
    # Science & Education
    "science": ["Science explains the world!", "Discovery!", "Knowledge!"],
    "physics": ["Physics is fundamental!", "Forces and energy!", "Universe!"],
    "chemistry": ["Chemistry is elemental!", "Reactions!", "Molecules!"],
    "biology": ["Biology is life science!", "Living things!", "Nature!"],
    "math": ["Math is universal!", "Numbers!", "Problem solving!"],
    "mathematics": ["Mathematics is logical!", "Calculations!", "Patterns!"],
    "history": ["History teaches us!", "The past!", "Learning from before!"],
    "geography": ["Geography explores Earth!", "Places!", "Maps!"],
    "astronomy": ["Astronomy studies space!", "Stars and planets!", "Universe!"],
    "psychology": ["Psychology studies mind!", "Behavior!", "Mental!"],
    "philosophy": ["Philosophy asks big questions!", "Thinking!", "Wisdom!"],
    "literature": ["Literature is written art!", "Books!", "Stories!"],
    "language": ["Languages connect us!", "Communication!", "Culture!"],
    "art": ["Art expresses creativity!", "Visual!", "Expression!"],
    "education": ["Education empowers!", "Learning!", "Knowledge!"],
    "school": ["School is foundational!", "Learning!", "Education!"],
    "college": ["College expands horizons!", "Higher education!", "Degrees!"],
    "university": ["University is higher learning!", "Research!", "Degrees!"],
    "degree": ["Degrees show achievement!", "Education!", "Qualifications!"],
    "student": ["Students are learning!", "Education!", "Growth!"],
    "teacher": ["Teachers inspire!", "Education!", "Knowledge sharing!"],
    "professor": ["Professors are experts!", "University!", "Research!"],
    "research": ["Research discovers!", "Science!", "Knowledge!"],
    "experiment": ["Experiments test ideas!", "Science!", "Discovery!"],
    "theory": ["Theories explain!", "Science!", "Understanding!"],
    "hypothesis": ["Hypotheses are educated guesses!", "Science!", "Testing!"],
    "study": ["Studying builds knowledge!", "Learning!", "Education!"],
    "learn": ["Learning is lifelong!", "Growth!", "Knowledge!"],
    "knowledge": ["Knowledge is power!", "Learning!", "Wisdom!"],
    "wisdom": ["Wisdom is applied knowledge!", "Experience!", "Understanding!"],
    "fact": ["Facts are true!", "Evidence!", "Reality!"],
    "truth": ["Truth matters!", "Facts!", "Reality!"],
    "logic": ["Logic is reasoning!", "Thinking!", "Analysis!"],
    "critical thinking": ["Critical thinking analyzes!", "Reasoning!", "Evaluation!"],
    "creativity": ["Creativity innovates!", "Imagination!", "Ideas!"],
    "innovation": ["Innovation changes things!", "New ideas!", "Progress!"],
    "discovery": ["Discovery finds new things!", "Science!", "Exploration!"],
    "invention": ["Inventions create solutions!", "Innovation!", "Progress!"],
    
    # Programming & Development
    "python": ["Python is versatile!", "Easy to learn!", "Popular language!"],
    "javascript": ["JavaScript powers the web!", "Frontend and backend!", "Everywhere!"],
    "java": ["Java is enterprise!", "Object-oriented!", "Widely used!"],
    "csharp": ["C# is Microsoft!", ".NET!", "Game development!"],
    "cpp": ["C++ is powerful!", "Performance!", "System programming!"],
    "ruby": ["Ruby is elegant!", "Rails!", "Developer happiness!"],
    "php": ["PHP powers websites!", "WordPress!", "Web backend!"],
    "swift": ["Swift is for Apple!", "iOS development!", "Modern!"],
    "kotlin": ["Kotlin is Android!", "Modern Java!", "Google choice!"],
    "rust": ["Rust is safe and fast!", "Memory safety!", "Growing!"],
    "golang": ["Go is simple and fast!", "Google!", "Concurrency!"],
    "typescript": ["TypeScript adds types!", "JavaScript++!", "Safer code!"],
    "sql": ["SQL queries databases!", "Data!", "Essential!"],
    "html": ["HTML structures web!", "Markup!", "Fundamental!"],
    "css": ["CSS styles web!", "Design!", "Visual!"],
    "api": ["APIs connect services!", "Integration!", "Data exchange!"],
    "git": ["Git tracks code!", "Version control!", "Collaboration!"],
    "github": ["GitHub hosts code!", "Open source!", "Collaboration!"],
    "debug": ["Debugging fixes bugs!", "Problem solving!", "Essential skill!"],
    "framework": ["Frameworks speed development!", "Structure!", "Tools!"],
    "library": ["Libraries provide code!", "Reusable!", "Efficient!"],
    "frontend": ["Frontend is user-facing!", "UI!", "Visual!"],
    "backend": ["Backend is server-side!", "Logic!", "Database!"],
    "fullstack": ["Full stack does both!", "End to end!", "Versatile!"],
    "devops": ["DevOps bridges dev and ops!", "Automation!", "CI/CD!"],
    "agile": ["Agile is iterative!", "Methodology!", "Flexible!"],
    "scrum": ["Scrum is agile framework!", "Sprints!", "Team process!"],
}
