"""Travel, places, and geography responses"""

TRAVEL = {
    # Travel & Places
    "travel": ["Travel broadens the mind!", "Where have you been?", "Any dream destinations?"],
    "vacation": ["Vacations are essential!", "Where do you like to go?", "Rest and relaxation!"],
    "trip": ["Trips are adventures!", "Road trip or flight?", "Where to?"],
    "adventure": ["Adventures are thrilling!", "Explore the world!", "Try new things!"],
    "explore": ["Exploration is exciting!", "Discover new places!", "Curiosity!"],
    "journey": ["Every journey starts with a step!", "Life is a journey!", "Enjoy the ride!"],
    "destination": ["Destinations await!", "Where to?", "Goals!"],
    "beach": ["Beaches are relaxing!", "Sun and sand!", "Ocean vibes!"],
    "mountain": ["Mountains are majestic!", "Hiking!", "Views!"],
    "city": ["Cities are exciting!", "Urban life!", "So much to do!"],
    "country": ["Countries have unique cultures!", "Travel abroad!", "Diversity!"],
    "island": ["Islands are paradise!", "Tropical!", "Escape!"],
    "lake": ["Lakes are peaceful!", "Calm waters!", "Nature!"],
    "river": ["Rivers flow endlessly!", "Nature!", "Life source!"],
    "desert": ["Deserts are vast!", "Sand dunes!", "Extreme!"],
    "jungle": ["Jungles are wild!", "Biodiversity!", "Adventure!"],
    "forest": ["Forests are peaceful!", "Trees!", "Nature walks!"],
    "park": ["Parks are relaxing!", "Green spaces!", "Recreation!"],
    "zoo": ["Zoos have animals!", "Wildlife!", "Educational!"],
    "museum": ["Museums preserve history!", "Art and culture!", "Learning!"],
    "hotel": ["Hotels provide comfort!", "Accommodation!", "Rest!"],
    "airport": ["Airports connect the world!", "Flying!", "Travel hub!"],
    "airplane": ["Airplanes fly us places!", "Aviation!", "Quick travel!"],
    "flight": ["Flights take us far!", "Soaring!", "Destinations!"],
    "passport": ["Passports open doors!", "Travel document!", "International!"],
    "tourist": ["Tourists explore!", "Sightseeing!", "Travel!"],
    "sightseeing": ["Sightseeing is fun!", "Landmarks!", "Photos!"],
    "landmark": ["Landmarks are iconic!", "Must-see!", "History!"],
    "monument": ["Monuments commemorate!", "History!", "Impressive!"],
    "culture": ["Culture enriches!", "Diversity!", "Traditions!"],
    "language": ["Languages connect us!", "Communication!", "Learning!"],
    "souvenir": ["Souvenirs are memories!", "Keepsakes!", "Travel reminders!"],
    "backpacking": ["Backpacking is adventurous!", "Budget travel!", "Freedom!"],
    "camping": ["Camping connects with nature!", "Outdoors!", "Tents!"],
    "cruise": ["Cruises are luxurious!", "Ocean travel!", "All-inclusive!"],
    "road trip": ["Road trips are freedom!", "Driving!", "Adventure!"],
    "train": ["Trains are scenic!", "Rail travel!", "Relaxing!"],
    "bus": ["Buses are economical!", "Public transit!", "Travel!"],
    "car": ["Cars provide freedom!", "Driving!", "Road trips!"],
    "map": ["Maps guide us!", "Navigation!", "Directions!"],
    "gps": ["GPS navigates!", "Technology!", "Never lost!"],
    "guide": ["Guides show the way!", "Tours!", "Local knowledge!"],
    "tour": ["Tours are informative!", "Guided!", "Group travel!"],
    "itinerary": ["Itineraries plan trips!", "Schedule!", "Organization!"],
    "luggage": ["Luggage carries belongings!", "Packing!", "Travel bags!"],
    "suitcase": ["Suitcases hold clothes!", "Travel!", "Packing!"],
    "backpack": ["Backpacks are versatile!", "Hands-free!", "Hiking and travel!"],
    
    # Languages & Countries
    "english": ["English is global!", "Language!", "Communication!"],
    "spanish": ["Spanish is beautiful!", "Language!", "Hispanic culture!"],
    "french": ["French is romantic!", "Language!", "Ooh la la!"],
    "german": ["German is precise!", "Language!", "Guten Tag!"],
    "italian": ["Italian is melodic!", "Language!", "Ciao!"],
    "portuguese": ["Portuguese is widespread!", "Language!", "Brazil and Portugal!"],
    "chinese": ["Chinese is ancient!", "Language!", "Many dialects!"],
    "japanese": ["Japanese is unique!", "Language!", "Kanji!"],
    "korean": ["Korean is trending!", "Language!", "Hallyu!"],
    "arabic": ["Arabic is beautiful!", "Language!", "Calligraphy!"],
    "russian": ["Russian is vast!", "Language!", "Cyrillic!"],
    "hindi": ["Hindi is spoken by millions!", "Language!", "India!"],
    "america": ["America is diverse!", "USA!", "Land of opportunity!"],
    "england": ["England has history!", "UK!", "Tea and royalty!"],
    "france": ["France has culture!", "Paris!", "Art and cuisine!"],
    "germany": ["Germany is efficient!", "Europe!", "History and engineering!"],
    "italy": ["Italy has heritage!", "Rome!", "Art and food!"],
    "spain": ["Spain has passion!", "Madrid!", "Flamenco!"],
    "japan": ["Japan blends old and new!", "Tokyo!", "Technology and tradition!"],
    "china": ["China has ancient history!", "Beijing!", "Culture!"],
    "australia": ["Australia is unique!", "Outback!", "Wildlife!"],
    "canada": ["Canada is friendly!", "Maple syrup!", "Nature!"],
    "brazil": ["Brazil is vibrant!", "Carnival!", "Soccer!"],
    "india": ["India is colorful!", "Diversity!", "Rich culture!"],
    "mexico": ["Mexico has culture!", "Tacos!", "History!"],
    "russia": ["Russia is vast!", "Moscow!", "History!"],
    "korea": ["Korea is innovative!", "Seoul!", "K-culture!"],
    "europe": ["Europe has history!", "Diverse countries!", "Travel!"],
    "asia": ["Asia is vast!", "Many cultures!", "Ancient history!"],
    "africa": ["Africa is diverse!", "Wildlife!", "Rich cultures!"],
    "south america": ["South America is vibrant!", "Rainforests!", "Culture!"],
    "north america": ["North America is diverse!", "USA and Canada!", "Nature!"],
    "antarctica": ["Antarctica is frozen!", "Penguins!", "Extreme!"],
    "arctic": ["The Arctic is cold!", "Polar bears!", "Ice!"],
    "paris": ["Paris is romantic!", "Eiffel Tower!", "City of Light!"],
    "london": ["London is historic!", "Big Ben!", "Royal!"],
    "tokyo": ["Tokyo is modern!", "Technology!", "Culture!"],
    "new york": ["New York is exciting!", "Big Apple!", "City that never sleeps!"],
    "los angeles": ["LA is entertainment!", "Hollywood!", "Beaches!"],
    "sydney": ["Sydney is beautiful!", "Opera House!", "Beaches!"],
    "rome": ["Rome is ancient!", "Colosseum!", "History!"],
    "dubai": ["Dubai is luxurious!", "Modern!", "Desert oasis!"],
    "singapore": ["Singapore is clean!", "Modern!", "Melting pot!"],
    "bangkok": ["Bangkok is vibrant!", "Temples!", "Street food!"],
    "barcelona": ["Barcelona has art!", "Gaudi!", "Beaches!"],
    "amsterdam": ["Amsterdam has canals!", "Bikes!", "Culture!"],
    "berlin": ["Berlin has history!", "Wall!", "Culture!"],
    "prague": ["Prague is charming!", "Architecture!", "Affordable!"],
    "vienna": ["Vienna is musical!", "Mozart!", "Elegant!"],
    "venice": ["Venice has canals!", "Gondolas!", "Romance!"],
    "florence": ["Florence has art!", "Renaissance!", "Tuscany!"],
    "cairo": ["Cairo has pyramids!", "Ancient Egypt!", "History!"],
    "cape town": ["Cape Town has beauty!", "Mountains and ocean!", "South Africa!"],
    "rio": ["Rio has carnival!", "Christ the Redeemer!", "Beaches!"],
    "buenos aires": ["Buenos Aires has tango!", "Culture!", "Argentina!"],
    "hong kong": ["Hong Kong is dynamic!", "Skyline!", "East meets West!"],
    "seoul": ["Seoul is modern!", "K-pop!", "Technology!"],
    "mumbai": ["Mumbai is bustling!", "Bollywood!", "India!"],
    "istanbul": ["Istanbul bridges continents!", "History!", "Culture!"],
    "moscow": ["Moscow is grand!", "Red Square!", "Russia!"],
    "athens": ["Athens is ancient!", "Acropolis!", "Greece!"],
    "hawaii": ["Hawaii is paradise!", "Beaches!", "Aloha!"],
    "bali": ["Bali is spiritual!", "Beaches!", "Indonesia!"],
    "maldives": ["Maldives is luxurious!", "Overwater bungalows!", "Paradise!"],
    "thailand": ["Thailand is beautiful!", "Temples!", "Beaches!"],
    "vietnam": ["Vietnam has beauty!", "History!", "Cuisine!"],
    "egypt": ["Egypt has pyramids!", "Ancient!", "Pharaohs!"],
    "morocco": ["Morocco has markets!", "Colors!", "Spices!"],
    "kenya": ["Kenya has safari!", "Wildlife!", "Africa!"],
    "peru": ["Peru has Machu Picchu!", "Ancient!", "Mountains!"],
    "costa rica": ["Costa Rica has nature!", "Biodiversity!", "Pura vida!"],
    "iceland": ["Iceland has landscapes!", "Northern lights!", "Unique!"],
    "switzerland": ["Switzerland has Alps!", "Chocolate!", "Watches!"],
    "greece": ["Greece has islands!", "History!", "Santorini!"],
    "croatia": ["Croatia has coastline!", "Dubrovnik!", "Beautiful!"],
    "portugal": ["Portugal has charm!", "Lisbon!", "Port wine!"],
    "ireland": ["Ireland is green!", "Pubs!", "Friendly!"],
    "scotland": ["Scotland has highlands!", "Castles!", "Whisky!"],
    "new zealand": ["New Zealand is stunning!", "Middle Earth!", "Adventure!"],
    "philippines": ["Philippines has islands!", "Beaches!", "Friendly!"],
    "malaysia": ["Malaysia is diverse!", "Kuala Lumpur!", "Food!"],
    "indonesia": ["Indonesia has islands!", "Bali!", "Diverse!"],
}
