"""Work, professions, business, and career responses"""

WORK = {
    # Professions & Work
    "work": ["Work is important!", "What do you do?", "Career goals?"],
    "job": ["Jobs provide purpose!", "What's your job?", "Employment!"],
    "career": ["Careers are journeys!", "What field?", "Professional growth!"],
    "office": ["Offices are workplaces!", "Work environment!", "9 to 5!"],
    "boss": ["Bosses lead teams!", "Management!", "Leadership!"],
    "employee": ["Employees do the work!", "Staff!", "Team members!"],
    "salary": ["Salary compensates work!", "Pay!", "Earnings!"],
    "money": ["Money is a tool!", "Finance!", "Currency!"],
    "business": ["Business drives economy!", "Commerce!", "Entrepreneurship!"],
    "company": ["Companies employ people!", "Organizations!", "Business!"],
    "meeting": ["Meetings coordinate!", "Communication!", "Collaboration!"],
    "project": ["Projects have goals!", "Tasks!", "Deadlines!"],
    "deadline": ["Deadlines motivate!", "Due dates!", "Pressure!"],
    "success": ["Success is earned!", "Achievement!", "Goals!"],
    "failure": ["Failure teaches!", "Learn and grow!", "Stepping stone!"],
    
    # More Professions
    "doctor": ["Doctors heal!", "Healthcare!", "Medicine!"],
    "nurse": ["Nurses care!", "Healthcare!", "Compassion!"],
    "lawyer": ["Lawyers advocate!", "Legal!", "Justice!"],
    "engineer": ["Engineers build!", "Design!", "Problem-solving!"],
    "teacher": ["Teachers inspire!", "Education!", "Knowledge sharing!"],
    "scientist": ["Scientists discover!", "Research!", "Innovation!"],
    "artist": ["Artists create!", "Creativity!", "Expression!"],
    "writer": ["Writers tell stories!", "Words!", "Creativity!"],
    "musician": ["Musicians make music!", "Talent!", "Performance!"],
    "chef": ["Chefs cook!", "Culinary!", "Delicious!"],
    "architect": ["Architects design buildings!", "Structures!", "Vision!"],
    "pilot": ["Pilots fly!", "Aviation!", "Sky!"],
    "firefighter": ["Firefighters save lives!", "Bravery!", "Emergency!"],
    "police": ["Police protect!", "Law enforcement!", "Safety!"],
    "soldier": ["Soldiers serve!", "Military!", "Courage!"],
    "farmer": ["Farmers grow food!", "Agriculture!", "Essential!"],
    "mechanic": ["Mechanics fix things!", "Technical!", "Hands-on!"],
    "electrician": ["Electricians wire things!", "Power!", "Technical!"],
    "plumber": ["Plumbers fix pipes!", "Water!", "Essential!"],
    "carpenter": ["Carpenters build with wood!", "Craftsmanship!", "Construction!"],
    "painter": ["Painters add color!", "Art or walls!", "Creative!"],
    "photographer": ["Photographers capture moments!", "Images!", "Visual art!"],
    "journalist": ["Journalists report news!", "Information!", "Truth!"],
    "accountant": ["Accountants manage finances!", "Numbers!", "Tax!"],
    "manager": ["Managers lead teams!", "Coordination!", "Leadership!"],
    "ceo": ["CEOs run companies!", "Leadership!", "Executive!"],
    "entrepreneur": ["Entrepreneurs start businesses!", "Innovation!", "Risk-taking!"],
    "designer": ["Designers create!", "Visual!", "Creative!"],
    "developer": ["Developers code!", "Software!", "Building!"],
    "analyst": ["Analysts examine data!", "Insights!", "Research!"],
    "consultant": ["Consultants advise!", "Expertise!", "Solutions!"],
    "salesperson": ["Salespeople sell!", "Revenue!", "Persuasion!"],
    "marketer": ["Marketers promote!", "Branding!", "Strategy!"],
    "hr": ["HR manages people!", "Human resources!", "Recruitment!"],
    "receptionist": ["Receptionists greet!", "Front desk!", "Communication!"],
    "secretary": ["Secretaries assist!", "Administration!", "Organization!"],
    "assistant": ["Assistants support!", "Help!", "Organization!"],
    "intern": ["Interns learn!", "Entry level!", "Experience!"],
    "volunteer": ["Volunteers give time!", "Helping!", "Community!"],
    "freelancer": ["Freelancers work independently!", "Flexibility!", "Self-employed!"],
    "contractor": ["Contractors take projects!", "Temporary!", "Skilled!"],
    
    # Business & Finance
    "investment": ["Investments grow money!", "Finance!", "Returns!"],
    "stock": ["Stocks are ownership!", "Market!", "Trading!"],
    "market": ["Markets trade!", "Economy!", "Supply and demand!"],
    "bank": ["Banks hold money!", "Finance!", "Services!"],
    "loan": ["Loans are borrowed money!", "Interest!", "Debt!"],
    "credit": ["Credit is borrowed power!", "Cards!", "Score!"],
    "debt": ["Debt is owed money!", "Manage it!", "Repayment!"],
    "budget": ["Budgets plan spending!", "Finance!", "Control!"],
    "tax": ["Taxes fund society!", "Government!", "Obligation!"],
    "profit": ["Profit is gain!", "Revenue minus costs!", "Business!"],
    "loss": ["Loss is negative!", "Business risk!", "Learning!"],
    "revenue": ["Revenue is income!", "Sales!", "Business!"],
    "expense": ["Expenses are costs!", "Spending!", "Budget!"],
    "audit": ["Audits verify!", "Accounting!", "Compliance!"],
    "contract": ["Contracts are agreements!", "Legal!", "Business!"],
    "negotiation": ["Negotiation finds middle ground!", "Deals!", "Communication!"],
    "partnership": ["Partnerships combine forces!", "Collaboration!", "Business!"],
    "merger": ["Mergers combine companies!", "Growth!", "Business!"],
    "acquisition": ["Acquisitions buy companies!", "Expansion!", "Business!"],
    "startup": ["Startups innovate!", "New business!", "Risk!"],
    "funding": ["Funding provides capital!", "Investment!", "Growth!"],
    "venture": ["Ventures are risky!", "Investment!", "Startups!"],
    "angel": ["Angel investors fund early!", "Startups!", "Capital!"],
    "ipo": ["IPOs go public!", "Stock market!", "Big moment!"],
    "dividend": ["Dividends share profits!", "Stocks!", "Income!"],
    "portfolio": ["Portfolios hold investments!", "Diversification!", "Strategy!"],
    "asset": ["Assets have value!", "Ownership!", "Wealth!"],
    "liability": ["Liabilities are owed!", "Debt!", "Obligations!"],
    "equity": ["Equity is ownership!", "Value!", "Shares!"],
    "roi": ["ROI measures return!", "Investment!", "Performance!"],
    "cash flow": ["Cash flow is money movement!", "Business!", "Liquidity!"],
    "balance sheet": ["Balance sheets show finances!", "Accounting!", "Health!"],
    "income statement": ["Income statements show profit!", "Accounting!", "Performance!"],
    "forecast": ["Forecasts predict future!", "Planning!", "Strategy!"],
    "strategy": ["Strategy plans success!", "Business!", "Goals!"],
    "marketing": ["Marketing promotes!", "Advertising!", "Sales!"],
    "branding": ["Branding creates identity!", "Logo!", "Recognition!"],
    "advertising": ["Advertising spreads word!", "Promotion!", "Reach!"],
    "sales": ["Sales generate revenue!", "Business!", "Growth!"],
    "customer": ["Customers buy!", "Business!", "Service!"],
    "client": ["Clients are customers!", "Business!", "Relationships!"],
    "service": ["Services provide value!", "Business!", "Help!"],
    "product": ["Products are sold!", "Goods!", "Business!"],
    "manufacturing": ["Manufacturing makes things!", "Production!", "Industry!"],
    "supply chain": ["Supply chains move goods!", "Logistics!", "Business!"],
    "logistics": ["Logistics coordinates movement!", "Shipping!", "Efficiency!"],
    "warehouse": ["Warehouses store goods!", "Storage!", "Distribution!"],
    "inventory": ["Inventory tracks stock!", "Products!", "Management!"],
    "retail": ["Retail sells to consumers!", "Stores!", "Shopping!"],
    "wholesale": ["Wholesale sells in bulk!", "B2B!", "Distribution!"],
    "ecommerce": ["Ecommerce sells online!", "Digital!", "Shopping!"],
    "subscription": ["Subscriptions recur!", "Model!", "Revenue!"],
    "franchise": ["Franchises replicate!", "Business model!", "Brand!"],
    "corporation": ["Corporations are large!", "Business!", "Structure!"],
    "llc": ["LLCs limit liability!", "Business structure!", "Protection!"],
    "sole proprietor": ["Sole proprietors own alone!", "Small business!", "Simple!"],
    "nonprofit": ["Nonprofits serve causes!", "Charity!", "Mission!"],
    "board": ["Boards govern!", "Directors!", "Leadership!"],
    "shareholder": ["Shareholders own stock!", "Investors!", "Voting!"],
    "stakeholder": ["Stakeholders have interest!", "Affected parties!", "Involvement!"],
    
    # Legal
    "law": ["Law governs society!", "Rules!", "Justice!"],
    "court": ["Courts decide cases!", "Legal!", "Justice!"],
    "judge": ["Judges rule!", "Legal authority!", "Decision!"],
    "jury": ["Juries decide guilt!", "Citizens!", "Trial!"],
    "trial": ["Trials determine outcomes!", "Legal!", "Evidence!"],
    "verdict": ["Verdicts are decisions!", "Guilty or not!", "Outcome!"],
    "sentence": ["Sentences are punishments!", "Legal!", "Consequences!"],
    "crime": ["Crimes break laws!", "Illegal!", "Consequences!"],
    "criminal": ["Criminals break laws!", "Offenders!", "Justice!"],
    "victim": ["Victims suffer crimes!", "Harm!", "Support!"],
    "evidence": ["Evidence proves things!", "Facts!", "Court!"],
    "witness": ["Witnesses testify!", "See events!", "Court!"],
    "testimony": ["Testimony is statements!", "Court!", "Evidence!"],
    "attorney": ["Attorneys practice law!", "Lawyers!", "Legal!"],
    "prosecutor": ["Prosecutors charge crimes!", "Government!", "Criminal!"],
    "defendant": ["Defendants are accused!", "Trial!", "Defense!"],
    "plaintiff": ["Plaintiffs bring suits!", "Civil!", "Accuser!"],
    "lawsuit": ["Lawsuits are legal actions!", "Civil!", "Dispute!"],
    "settlement": ["Settlements resolve disputes!", "Agreement!", "Out of court!"],
    "appeal": ["Appeals challenge decisions!", "Higher court!", "Review!"],
    "constitution": ["Constitution is supreme law!", "Rights!", "Foundation!"],
    "amendment": ["Amendments change laws!", "Updates!", "Rights!"],
    "rights": ["Rights are freedoms!", "Protected!", "Law!"],
    "civil": ["Civil law handles disputes!", "Non-criminal!", "Private!"],
    "criminal": ["Criminal law punishes!", "Crimes!", "Government!"],
    "patent": ["Patents protect inventions!", "Intellectual property!", "Exclusive!"],
    "copyright": ["Copyright protects creations!", "Intellectual property!", "Rights!"],
    "trademark": ["Trademarks protect brands!", "Logos!", "Names!"],
    "regulation": ["Regulations are rules!", "Government!", "Compliance!"],
    "compliance": ["Compliance follows rules!", "Legal!", "Required!"],
    "liability": ["Liability is responsibility!", "Legal!", "Risk!"],
    "negligence": ["Negligence is carelessness!", "Tort!", "Liability!"],
    "malpractice": ["Malpractice is professional negligence!", "Doctors, lawyers!", "Liability!"],
    
    # Medical
    "hospital": ["Hospitals treat patients!", "Healthcare!", "Medical care!"],
    "clinic": ["Clinics provide care!", "Healthcare!", "Outpatient!"],
    "surgery": ["Surgery operates!", "Medical!", "Procedure!"],
    "diagnosis": ["Diagnosis identifies illness!", "Medical!", "Treatment!"],
    "treatment": ["Treatment heals!", "Medical!", "Recovery!"],
    "prescription": ["Prescriptions authorize medicine!", "Doctor!", "Pharmacy!"],
    "pharmacy": ["Pharmacies dispense medicine!", "Drugs!", "Healthcare!"],
    "medicine": ["Medicine heals!", "Drugs!", "Healthcare!"],
    "drug": ["Drugs treat conditions!", "Pharmaceutical!", "Medicine!"],
    "vaccine": ["Vaccines prevent disease!", "Immunization!", "Protection!"],
    "immunization": ["Immunization protects!", "Vaccines!", "Prevention!"],
    "symptom": ["Symptoms indicate illness!", "Signs!", "Diagnosis!"],
    "disease": ["Diseases are illnesses!", "Medical!", "Treatment!"],
    "condition": ["Conditions are health states!", "Medical!", "Chronic!"],
    "chronic": ["Chronic means long-term!", "Ongoing!", "Management!"],
    "acute": ["Acute means sudden!", "Severe!", "Short-term!"],
    "emergency": ["Emergencies need immediate care!", "Urgent!", "911!"],
    "ambulance": ["Ambulances transport patients!", "Emergency!", "Quick!"],
    "paramedic": ["Paramedics give first aid!", "Emergency!", "Life-saving!"],
    "icu": ["ICU is intensive care!", "Critical!", "Monitoring!"],
    "er": ["ER is emergency room!", "Urgent!", "Hospital!"],
    "patient": ["Patients receive care!", "Healthcare!", "Medical!"],
    "examination": ["Examinations check health!", "Checkup!", "Diagnosis!"],
    "checkup": ["Checkups are routine!", "Prevention!", "Health!"],
    "specialist": ["Specialists have expertise!", "Doctors!", "Focus area!"],
    "surgeon": ["Surgeons operate!", "Medical!", "Skilled!"],
    "anesthesia": ["Anesthesia numbs!", "Surgery!", "Pain-free!"],
    "recovery": ["Recovery is healing!", "After treatment!", "Time!"],
    "rehab": ["Rehab restores function!", "Physical therapy!", "Recovery!"],
    "physical therapy": ["PT helps mobility!", "Rehabilitation!", "Exercise!"],
    "mental health": ["Mental health matters!", "Psychology!", "Wellness!"],
    "psychiatry": ["Psychiatry treats mental illness!", "Medicine!", "Therapy!"],
    "psychology": ["Psychology studies mind!", "Behavior!", "Therapy!"],
    "counseling": ["Counseling provides support!", "Talk therapy!", "Help!"],
    "dentist": ["Dentists fix teeth!", "Oral health!", "Checkups!"],
    "orthodontist": ["Orthodontists straighten teeth!", "Braces!", "Alignment!"],
    "optometrist": ["Optometrists check eyes!", "Vision!", "Glasses!"],
    "dermatologist": ["Dermatologists treat skin!", "Skin care!", "Medical!"],
    "cardiologist": ["Cardiologists treat hearts!", "Cardiology!", "Heart health!"],
    "neurologist": ["Neurologists treat nerves!", "Brain!", "Nervous system!"],
    "oncologist": ["Oncologists treat cancer!", "Oncology!", "Specialized!"],
    "pediatrician": ["Pediatricians treat children!", "Kids!", "Healthcare!"],
    "gynecologist": ["Gynecologists treat women!", "Women's health!", "Reproductive!"],
    "urologist": ["Urologists treat urinary!", "Kidneys!", "Bladder!"],
    "radiologist": ["Radiologists read scans!", "Imaging!", "Diagnosis!"],
    "pathologist": ["Pathologists study disease!", "Lab!", "Diagnosis!"],
    "pharmacist": ["Pharmacists dispense drugs!", "Medication!", "Advice!"],
    "nurse practitioner": ["NPs provide care!", "Advanced nursing!", "Diagnosis!"],
    "physician assistant": ["PAs assist doctors!", "Medical care!", "Team!"],
    
    # Construction
    "construction": ["Construction builds!", "Building!", "Infrastructure!"],
    "building": ["Buildings are structures!", "Architecture!", "Construction!"],
    "foundation": ["Foundations support!", "Base!", "Essential!"],
    "frame": ["Frames give structure!", "Skeleton!", "Building!"],
    "roof": ["Roofs cover!", "Protection!", "Shelter!"],
    "wall": ["Walls divide and support!", "Structure!", "Rooms!"],
    "floor": ["Floors are walking surfaces!", "Ground!", "Levels!"],
    "ceiling": ["Ceilings are overhead!", "Interior!", "Height!"],
    "window": ["Windows let light in!", "Glass!", "Views!"],
    "door": ["Doors provide access!", "Entry!", "Exit!"],
    "beam": ["Beams support weight!", "Structure!", "Steel or wood!"],
    "column": ["Columns support vertically!", "Structure!", "Pillars!"],
    "concrete": ["Concrete is strong!", "Building material!", "Foundations!"],
    "steel": ["Steel is strong!", "Metal!", "Structure!"],
    "brick": ["Bricks build walls!", "Masonry!", "Classic!"],
    "wood": ["Wood is versatile!", "Lumber!", "Building!"],
    "insulation": ["Insulation saves energy!", "Temperature!", "Efficiency!"],
    "plumbing": ["Plumbing moves water!", "Pipes!", "Essential!"],
    "electrical": ["Electrical powers buildings!", "Wiring!", "Lights!"],
    "hvac": ["HVAC heats and cools!", "Climate control!", "Comfort!"],
    "permit": ["Permits authorize work!", "Legal!", "Construction!"],
    "blueprint": ["Blueprints are plans!", "Design!", "Architecture!"],
    "contractor": ["Contractors manage construction!", "Building!", "Projects!"],
    "subcontractor": ["Subcontractors specialize!", "Specific work!", "Construction!"],
    "renovation": ["Renovation updates!", "Remodeling!", "Improvement!"],
    "remodel": ["Remodeling changes spaces!", "Renovation!", "Update!"],
    "demolition": ["Demolition tears down!", "Destruction!", "Clearing!"],
    "excavation": ["Excavation digs!", "Foundation!", "Earthwork!"],
    "scaffolding": ["Scaffolding supports workers!", "Temporary!", "Height!"],
    "crane": ["Cranes lift heavy loads!", "Equipment!", "Construction!"],
    "bulldozer": ["Bulldozers push earth!", "Heavy equipment!", "Clearing!"],
    "excavator": ["Excavators dig!", "Heavy equipment!", "Earth moving!"],
    "cement": ["Cement binds!", "Concrete ingredient!", "Building!"],
    "mortar": ["Mortar bonds bricks!", "Masonry!", "Building!"],
    "drywall": ["Drywall makes walls!", "Interior!", "Finishing!"],
    "paint": ["Paint colors surfaces!", "Finishing!", "Decoration!"],
    "tile": ["Tiles cover surfaces!", "Flooring!", "Bathrooms!"],
    "hardwood": ["Hardwood is quality flooring!", "Wood floors!", "Elegant!"],
    "carpet": ["Carpet is soft flooring!", "Comfortable!", "Cozy!"],
    "laminate": ["Laminate is affordable flooring!", "Durable!", "Easy!"],
}
