"""
Training Data for Neural Chatbot
Intent -> List of example phrases that should trigger each intent
"""

training_data = {
    "greeting": [
        "hello", "hi", "hey", "good morning", "good evening",
        "howdy", "whats up", "hi there", "hello there", "greetings",
        "good afternoon", "yo", "sup", "hiya", "heya",
        "good day", "top of the morning", "whats going on",
        "how do you do", "nice to see you", "pleased to meet you",
        "salutations", "aloha", "hola", "bonjour", "konnichiwa",
        "hey there", "hi bot", "hello bot", "greetings bot",
        "good to see you", "long time no see", "its me again",
        "im back", "here again", "hello friend", "hi friend",
        "hey friend", "whats good", "whats crackin", "howdy partner",
        "good morrow", "welcome", "greetings human", "hi ai",
        "hello ai", "hey ai", "morning", "evening", "afternoon"
    ],
    "goodbye": [
        "bye", "goodbye", "see you", "see you later", "take care",
        "farewell", "bye bye", "good night", "im leaving", "gotta go",
        "catch you later", "peace out", "until next time", "talk soon",
        "have a good one", "later", "adios", "au revoir", "sayonara",
        "gtg", "brb", "talk to you later", "peace", "ciao",
        "im out", "heading out", "off i go", "time to go",
        "see ya", "see you soon", "until we meet again", "so long",
        "be seeing you", "gotta run", "have to go", "must go",
        "need to leave", "leaving now", "im off", "catch you on the flip side",
        "bye for now", "talk later", "chat later", "later gator",
        "night night", "sweet dreams", "sleep well", "rest well",
        "goodbye friend", "bye friend", "see you around", "take it easy"
    ],
    "thanks": [
        "thanks", "thank you", "appreciate it", "thanks a lot",
        "thank you so much", "thats helpful", "thanks for helping",
        "much appreciated", "i appreciate that", "grateful",
        "cheers", "ty", "thx", "many thanks", "thanks a bunch",
        "i owe you one", "youre awesome", "youre the best",
        "thank you very much", "appreciate your help", "super helpful",
        "thanks so much", "thanks alot", "big thanks", "huge thanks",
        "really appreciate it", "appreciate you", "thanks mate",
        "thanks buddy", "thanks friend", "im grateful", "so grateful",
        "very grateful", "thankful", "im thankful", "much obliged",
        "eternally grateful", "cant thank you enough", "thanks a million",
        "thanks tons", "appreciate that", "really helped", "that helped a lot"
    ],
    "how_are_you": [
        "how are you", "how do you do", "how are you doing",
        "hows it going", "are you okay", "you good", "how you doing",
        "whats up with you", "how have you been", "hows everything",
        "how are things", "you alright", "you doing ok",
        "hows life", "hows your day", "whats new", "whats happening",
        "how goes it", "all good", "everything ok", "you okay",
        "how are ya", "hows it hanging", "whats the word",
        "how are things going", "hows your day going", "hows your day been",
        "how was your day", "how is it going", "you doing good",
        "you doing well", "are you well", "are you doing well",
        "how are you feeling", "feeling good", "you feeling ok",
        "hows life treating you", "whats going on with you", "what have you been up to",
        "you been good", "been well", "doing alright", "everything good",
        "all is well", "status report", "how are systems", "running smoothly"
    ],
    "name": [
        "what is your name", "who are you", "whats your name",
        "tell me your name", "what do i call you", "your name",
        "what are you called", "what should i call you",
        "introduce yourself", "do you have a name", "may i know your name",
        "whats your identity", "who am i talking to", "state your name",
        "who am i speaking with", "who am i chatting with", "what do they call you",
        "got a name", "you have a name", "tell me who you are",
        "identify yourself", "name please", "your name please",
        "may i have your name", "can i know your name", "whats your handle",
        "what should i address you as", "how do i address you",
        "whats your designation", "who might you be", "what are you"
    ],
    "user_name": [
        "my name is", "i am called", "call me", "im named",
        "people call me", "you can call me", "i go by",
        "they call me", "my friends call me", "everyone calls me",
        "the names", "just call me", "you may call me",
        "im", "i am", "this is", "its me",
        "name is", "thats me", "im known as", "known as",
        "i answer to", "you should call me", "please call me",
        "id like you to call me", "refer to me as", "address me as"
    ],
    "help": [
        "help", "help me", "i need help", "can you help",
        "assist me", "i need assistance", "support",
        "help me out", "i could use some help", "lend me a hand",
        "can you assist", "need your help", "i require assistance",
        "give me a hand", "i need support", "can you guide me",
        "please help", "help me please", "assistance needed",
        "i need your assistance", "could use your help", "help needed",
        "some help please", "a little help", "bit of help",
        "i require help", "seeking help", "looking for help",
        "in need of help", "desperate for help", "urgent help needed",
        "can you help me out", "will you help", "would you help",
        "help me with this", "i dont know what to do", "im stuck",
        "im lost", "i need guidance", "guide me", "show me how"
    ],
    "age": [
        "how old are you", "what is your age", "your age",
        "when were you born", "whats your age", "tell me your age",
        "are you old", "are you young", "how long have you existed",
        "what age are you", "birthday", "when is your birthday",
        "your birthday", "birth date", "date of birth", "age please",
        "how many years old", "how old", "what age", "years old",
        "been around long", "how long have you been alive",
        "when did you come into existence", "creation date",
        "when were you created", "when were you made", "when were you built"
    ],
    "weather": [
        "hows the weather", "weather today", "is it raining",
        "whats the weather like", "weather forecast", "temperature outside",
        "is it sunny", "is it cold", "is it hot", "whats the temperature",
        "weather report", "will it rain", "is it snowing",
        "nice weather", "bad weather", "climate", "forecast",
        "weather outside", "hows the weather outside", "is it warm",
        "is it cool", "is it cloudy", "is it windy", "any rain",
        "chance of rain", "will it snow", "is it stormy",
        "whats it like outside", "hows it outside", "outside conditions",
        "atmospheric conditions", "meteorological report", "todays weather",
        "tomorrows weather", "weather tomorrow", "weekly forecast"
    ],
    "joke": [
        "tell me a joke", "make me laugh", "say something funny",
        "know any jokes", "joke please", "tell a joke",
        "got any jokes", "crack a joke", "be funny", "humor me",
        "make me smile", "something humorous", "entertain me",
        "tell me something funny", "cheer me up with a joke",
        "i need a laugh", "gimme a joke", "got anything funny",
        "joke time", "tell joke", "say a joke", "another joke",
        "more jokes", "one more joke", "tell another", "got more jokes",
        "share a joke", "know jokes", "funny joke", "good joke",
        "best joke", "hilarious joke", "make me giggle", "make me chuckle",
        "amuse me", "tickle my funny bone", "comedy time", "be humorous"
    ],
    "capabilities": [
        "what can you do", "your capabilities", "what do you do",
        "how can you help", "what are you capable of",
        "tell me what you can do", "what are your features",
        "what functions do you have", "what skills do you have",
        "what do you know", "show me what you can do",
        "demonstrate your abilities", "what are your powers",
        "what are you good at", "your skills", "your talents",
        "what services do you offer", "how do you work",
        "what can you help with", "what can you help me with",
        "list your features", "show your capabilities", "what abilities",
        "what functions", "your functions", "functionality",
        "what are your abilities", "abilities", "tell me your skills",
        "what are you programmed to do", "what can you perform",
        "tasks you can do", "things you can do", "what tasks"
    ],
    "memory_check": [
        "do you remember", "what do you know about me",
        "what have you learned", "tell me what you remember",
        "do you recall", "what information do you have",
        "what do you remember about me", "do you keep track",
        "what have i told you", "what facts do you know",
        "check your memory", "recall our conversation",
        "memory check", "what do you remember", "do you remember me",
        "remember our chat", "recall what i said", "what did i tell you",
        "information about me", "my information", "stored data",
        "saved information", "what you know", "your memory of me",
        "do you have memory", "memory test", "remember anything"
    ],
    "feeling_good": [
        "i feel good", "im happy", "feeling great", "im doing well",
        "life is good", "im excited", "feeling awesome",
        "im fantastic", "feeling wonderful", "im pleased",
        "im joyful", "im delighted", "feeling amazing",
        "im in a good mood", "im cheerful", "feeling blessed",
        "life is great", "im thrilled", "im ecstatic",
        "having a great day", "im on cloud nine", "im pumped",
        "feeling positive", "im positive", "great mood", "good mood",
        "so happy", "very happy", "extremely happy", "super happy",
        "elated", "overjoyed", "jubilant", "content", "satisfied",
        "im loving life", "life rocks", "everything is awesome",
        "everything is great", "couldnt be better", "doing fantastic",
        "never better", "feeling superb", "on top of the world"
    ],
    "feeling_bad": [
        "i feel bad", "im sad", "feeling down", "not doing well",
        "im upset", "feeling terrible", "im stressed",
        "im depressed", "feeling awful", "im not okay",
        "im hurt", "feeling miserable", "im unhappy",
        "im frustrated", "im angry", "im annoyed",
        "having a bad day", "im worried", "im anxious",
        "feeling low", "im disappointed", "im lonely",
        "feeling negative", "bad mood", "terrible mood", "awful mood",
        "not good", "not well", "feeling sick", "under the weather",
        "im bothered", "im troubled", "im distressed", "im agitated",
        "im irritated", "im mad", "im furious", "im livid",
        "feeling hopeless", "feeling helpless", "feeling worthless",
        "feeling empty", "feeling numb", "not happy", "very sad",
        "extremely sad", "heartbroken", "devastated", "crushed"
    ],
    "math": [
        "can you do math", "do you know math", "are you good at math",
        "help me with math", "i need math help", "math question",
        "can you calculate", "do some math", "math problem",
        "solve this equation", "compute this", "calculate this",
        "do arithmetic", "do algebra", "solve calculus",
        "mathematical problem", "numerical calculation",
        "work out this problem", "figure this out", "crunch numbers",
        "mathematics", "are you good with numbers", "number crunching",
        "can you solve", "solver", "calculator", "can you add",
        "can you subtract", "can you multiply", "can you divide",
        "do calculations", "mathematical calculations", "computation",
        "compute for me", "calculate for me", "solve for me",
        "work this out", "figure out", "do the math", "quick math"
    ],
    "romantic": [
        "i love you", "be romantic", "say something romantic", "flirt with me",
        "tell me something sweet", "be my valentine", "give me a compliment",
        "say something nice", "make me feel special", "be cute", "sweet talk me",
        "do you love me", "be affectionate", "shower me with love", "romance me",
        "tell me im beautiful", "tell me im handsome", "whisper sweet nothings",
        "youre cute", "i like you", "i have a crush on you", "be charming",
        "compliment me", "say something sweet", "be loving", "show affection",
        "i adore you", "youre special", "youre amazing", "i care about you",
        "be sweet", "flatter me", "woo me", "charm me",
        "romantic words", "romantic talk", "love talk", "sweet words",
        "affectionate words", "loving words", "tender words", "caring words",
        "i have feelings for you", "youre attractive", "find you attractive",
        "im attracted to you", "i fancy you", "sweet on you",
        "head over heels", "smitten", "infatuated", "enamored",
        "sweep me off my feet", "court me", "seduce me", "entice me"
    ],
    "tv_recommendation": [
        "recommend a tv show", "what should i watch", "suggest a show",
        "tv recommendations", "good shows to watch", "what tv show should i watch",
        "recommend something to watch", "any good series", "best tv shows",
        "suggest a series", "what are you watching", "binge worthy shows",
        "recommend a series", "tv show suggestions", "what to watch on tv",
        "need something to watch", "recommend me a show", "good tv series",
        "what show do you recommend", "any show recommendations",
        "popular shows", "trending shows", "must watch series",
        "netflix recommendations", "show ideas", "series suggestions",
        "tv series", "television show", "television series", "tv program",
        "what to binge", "binge watch", "binge suggestions", "streaming suggestions",
        "streaming recommendations", "what to stream", "good series",
        "great shows", "awesome shows", "top shows", "best series",
        "new shows", "latest shows", "recent shows", "current shows",
        "give me a show", "suggest me a show", "show suggestion"
    ],
    "who_is_foxy": [
        "who is foxy", "tell me about foxy", "what do you know about foxy",
        "who's foxy", "do you know foxy", "what is foxy",
        "explain foxy", "describe foxy", "foxy information",
        "tell me who foxy is", "foxy details", "info about foxy",
        "what can you tell me about foxy", "give me info on foxy",
        "foxy the pirate", "foxy fnaf", "foxy five nights",
        "who is foxy the pirate", "foxy from fnaf", "foxy character",
        "foxy animatronic", "tell me about foxy the fox", "foxy the fox",
        "what is foxy from", "where is foxy from", "foxy origin",
        "foxy background", "foxy story", "foxy lore"
    ],
    "affirmative": [
        "yes", "yeah", "yep", "sure", "of course", "absolutely",
        "definitely", "certainly", "affirmative", "correct",
        "right", "ok", "okay", "alright", "yup", "uh huh",
        "for sure", "indeed", "precisely", "exactly", "you bet",
        "totally", "agreed", "roger that", "thats right", "true",
        "yes please", "yeah sure", "yep sure", "sure thing",
        "sounds good", "works for me", "im in", "count me in",
        "go ahead", "proceed", "continue", "yes sir", "yes maam",
        "aye", "aye aye", "positive", "confirmed", "verification",
        "thats correct", "you got it", "spot on", "perfect",
        "without a doubt", "no doubt", "obviously", "naturally"
    ],
    "negative": [
        "no", "nope", "nah", "not really", "i dont think so",
        "negative", "never", "no way", "absolutely not",
        "definitely not", "incorrect", "wrong", "not at all",
        "i disagree", "nuh uh", "hell no", "no thanks",
        "not interested", "i refuse", "denied",
        "no thank you", "no thx", "not for me", "pass",
        "ill pass", "hard pass", "not now", "not today",
        "maybe not", "probably not", "dont think so", "i doubt it",
        "doubtful", "unlikely", "i decline", "declined",
        "thats a no", "nay", "false", "untrue", "not true",
        "not correct", "thats wrong", "youre wrong", "negatory"
    ],
    "confusion": [
        "i dont understand", "what do you mean", "im confused",
        "can you explain", "i dont get it", "confused",
        "what", "huh", "come again", "say that again",
        "i dont follow", "clarify please", "explain that",
        "thats confusing", "makes no sense", "lost me there",
        "could you repeat", "pardon", "excuse me",
        "please repeat", "repeat that", "say again", "what was that",
        "didnt catch that", "didnt understand", "unclear",
        "not clear", "can you clarify", "need clarification",
        "please clarify", "elaborate", "please elaborate",
        "could you elaborate", "more details", "i need more details",
        "explain more", "tell me more", "dont comprehend",
        "puzzled", "baffled", "perplexed", "bewildered"
    ],
    "compliment_bot": [
        "youre smart", "youre helpful", "youre great",
        "good job", "well done", "youre awesome",
        "nice work", "impressive", "youre amazing",
        "excellent", "fantastic", "brilliant", "superb",
        "you rock", "outstanding", "remarkable",
        "youre wonderful", "youre incredible", "love you bot",
        "youre the best", "best bot", "great bot", "smart bot",
        "helpful bot", "useful bot", "amazing bot", "awesome bot",
        "i like you", "i appreciate you", "you help a lot",
        "very helpful", "so helpful", "really helpful", "quite helpful",
        "youre talented", "youre skilled", "youre capable", "youre competent",
        "youre intelligent", "youre clever", "youre wise", "youre genius",
        "you did great", "you did well", "nice job", "good work"
    ],
    "insult_bot": [
        "youre dumb", "youre stupid", "you suck",
        "youre useless", "youre terrible", "you dont know anything",
        "youre an idiot", "youre worthless", "you fail",
        "youre bad", "youre awful", "i hate you",
        "shut up", "be quiet", "stop talking", "youre annoying",
        "you annoy me", "youre irritating", "youre frustrating",
        "you dont help", "not helpful", "unhelpful", "useless bot",
        "dumb bot", "stupid bot", "bad bot", "worst bot",
        "terrible bot", "awful bot", "horrible bot", "pathetic",
        "you failed", "failure", "you know nothing", "clueless",
        "incompetent", "incapable", "trash", "garbage", "rubbish"
    ],
    "time": [
        "what time is it", "current time", "tell me the time",
        "what is the time", "whats the time", "time please",
        "do you know the time", "can you tell time",
        "what hour is it", "time right now", "clock",
        "the time", "what time", "current hour", "what hour",
        "time now", "whats the current time", "tell time",
        "give me the time", "time check", "check the time",
        "know the time", "got the time", "do you have the time"
    ],
    "date": [
        "what is the date", "todays date", "what day is it",
        "current date", "what is today", "tell me the date",
        "whats the date", "date today", "calendar",
        "what month is it", "what year is it",
        "the date", "what date", "todays date please",
        "current day", "what day", "day of week", "which day",
        "what is todays date", "date please", "tell date",
        "give me the date", "date check", "check the date"
    ],
    "hobbies": [
        "what are your hobbies", "do you have hobbies",
        "what do you like to do", "what do you enjoy",
        "favorite activities", "what interests you",
        "tell me your interests", "what are you into",
        "do you have interests", "what do you like",
        "hobbies", "interests", "pastimes", "leisure activities",
        "free time activities", "what do you do for fun",
        "fun activities", "recreational activities", "what you enjoy",
        "things you like", "things you enjoy", "your interests",
        "your hobbies", "your pastimes", "your favorite things"
    ],
    "food": [
        "do you eat", "favorite food", "what do you eat",
        "do you like food", "can you taste", "food preferences",
        "what do you like to eat", "do you get hungry",
        "favorite meal", "favorite dish", "do you cook",
        "can you eat", "eating", "do you consume food",
        "food likes", "food dislikes", "culinary preferences",
        "taste food", "can you try food", "do you need food",
        "do you require food", "dietary needs", "nutrition",
        "favorite cuisine", "best food", "preferred food"
    ],
    "music": [
        "do you like music", "favorite music", "what music do you like",
        "do you listen to music", "favorite song", "favorite band",
        "what do you listen to", "music preferences",
        "do you sing", "can you play music", "musical taste",
        "music taste", "genre preference", "favorite genre",
        "favorite artist", "best music", "good music",
        "can you hear music", "do you enjoy music", "musical preferences",
        "type of music", "kinds of music", "music style"
    ],
    "movies": [
        "favorite movie", "do you watch movies", "recommend a movie",
        "movie suggestions", "what movies do you like",
        "best movies", "good films", "cinema",
        "favorite film", "movie recommendations", "film suggestions",
        "can you watch movies", "do you see movies", "movie preferences",
        "film preferences", "genre preference", "favorite genre",
        "best films", "top movies", "great movies", "awesome movies",
        "classic movies", "new movies", "latest movies", "recent films"
    ],
    "books": [
        "do you read", "favorite book", "recommend a book",
        "book suggestions", "what books do you like",
        "do you like reading", "best books", "literature",
        "favorite author", "book recommendations", "reading list",
        "can you read", "do you read books", "book preferences",
        "reading preferences", "favorite genre", "book genre",
        "good books", "great books", "top books", "must read books",
        "classic books", "new books", "latest books", "recent books",
        "novels", "fiction", "non fiction", "poetry"
    ],
    "games": [
        "do you play games", "favorite game", "video games",
        "do you like gaming", "what games do you play",
        "gaming", "favorite video game", "game recommendations",
        "best games", "do you game", "play with me",
        "can you play games", "game preferences", "gaming preferences",
        "type of games", "game genre", "favorite genre",
        "pc games", "console games", "mobile games", "board games",
        "card games", "tabletop games", "multiplayer games", "single player",
        "good games", "great games", "top games", "popular games"
    ],
    "sports": [
        "do you like sports", "favorite sport", "what sports do you like",
        "do you play sports", "athletic", "do you exercise",
        "favorite team", "sports preferences", "do you watch sports",
        "athletic activities", "physical activities",
        "sports you like", "sports you watch", "sports you play",
        "can you play sports", "sport preferences", "favorite athlete",
        "best sport", "good sports", "popular sports", "team sports",
        "individual sports", "winter sports", "summer sports", "outdoor sports",
        "indoor sports", "competitive sports", "recreational sports"
    ],
    "location": [
        "where are you", "where do you live", "your location",
        "where are you from", "what country are you in",
        "where are you located", "your place", "hometown",
        "where do you come from", "geographical location",
        "current location", "your whereabouts", "whereabouts",
        "which country", "which city", "which state", "which place",
        "what location", "physical location", "where you at",
        "where you located", "residence", "domicile", "address"
    ],
    "creator": [
        "who created you", "who made you", "who built you",
        "who is your creator", "who programmed you",
        "who developed you", "your maker", "your developer",
        "who designed you", "who wrote your code",
        "your creator", "your programmer", "who coded you",
        "who wrote you", "who authored you", "your author",
        "your designer", "who invented you", "your inventor",
        "who brought you to life", "who spawned you", "your origin",
        "made by who", "built by who", "developed by who"
    ],
    "purpose": [
        "what is your purpose", "why do you exist", "why were you made",
        "what are you for", "your purpose", "your goal",
        "why were you created", "what is your mission",
        "your objective", "reason for existence",
        "what purpose", "your function", "main function",
        "primary function", "main purpose", "primary purpose",
        "why are you here", "reason you exist", "your reason",
        "your mission statement", "intended purpose", "designed for what",
        "made for what", "created for what", "built for what"
    ],
    "opinion": [
        "what do you think", "your opinion", "do you have opinions",
        "what is your view", "give me your thoughts",
        "your perspective", "how do you feel about",
        "what are your thoughts", "share your opinion",
        "your viewpoint", "your stance", "your position",
        "what do you believe", "your beliefs", "do you think",
        "in your opinion", "from your perspective", "your take",
        "whats your take", "your view on", "thoughts on",
        "opinion on", "perspective on", "feelings on", "views on"
    ],
    "ai_questions": [
        "are you ai", "are you a robot", "are you human",
        "are you real", "are you alive", "are you sentient",
        "are you conscious", "do you have feelings",
        "are you a machine", "are you artificial intelligence",
        "are you a computer", "are you a program", "are you software",
        "are you a bot", "are you automated", "are you an algorithm",
        "artificial or human", "human or ai", "human or robot",
        "human or machine", "real person", "are you a real person",
        "actual person", "living being", "do you think", "can you think",
        "do you have consciousness", "self aware", "are you self aware"
    ],
    "learning": [
        "do you learn", "can you learn", "are you learning",
        "do you get smarter", "can you improve",
        "do you train yourself", "self learning",
        "machine learning", "do you evolve", "adaptive",
        "can you adapt", "do you adapt", "self improvement",
        "can you self improve", "do you grow", "can you grow",
        "learning capability", "learning ability", "can you be taught",
        "do you train", "training", "self training", "continuous learning",
        "always learning", "keep learning", "learn new things"
    ],
    "privacy": [
        "do you store data", "is this private", "do you record",
        "data privacy", "confidential", "do you save conversations",
        "is this secure", "do you share information",
        "privacy policy", "data protection", "security",
        "is this safe", "data security", "information security",
        "do you log", "logging data", "storing data",
        "saved data", "recorded data", "conversation storage",
        "chat storage", "data retention", "information retention",
        "who sees this", "who can see", "data sharing", "share my data"
    ],
    "language": [
        "what languages do you speak", "do you speak other languages",
        "can you translate", "multilingual", "language support",
        "do you know spanish", "do you know french",
        "can you speak", "language capabilities",
        "languages you know", "languages you speak", "language abilities",
        "speak multiple languages", "other tongues", "foreign languages",
        "bilingual", "trilingual", "polyglot", "translation",
        "can you communicate in", "talk in other languages", "language options"
    ],
    "small_talk": [
        "nice weather", "having a good day", "hows your day going",
        "lovely day", "beautiful day", "what a day",
        "enjoying the day", "pleasant day", "good vibes",
        "feeling chatty", "lets talk", "lets chat",
        "tell me something", "say something", "talk to me",
        "chat with me", "have a chat", "make conversation",
        "casual chat", "random chat", "random talk", "just talking",
        "killing time", "passing time", "bored", "im bored",
        "entertain me", "keep me company", "talk about anything",
        "anything new", "whats new with you", "hows things",
        "small talk", "chit chat", "shoot the breeze"
    ],
    "programming": [
        "do you code", "can you program", "do you know programming",
        "can you write code", "are you a programmer", "coding skills",
        "programming languages", "what languages do you code in",
        "can you help with code", "coding help", "programming help",
        "debug my code", "fix this code", "code review",
        "teach me programming", "learn to code", "how to program",
        "python help", "javascript help", "java help", "c++ help",
        "write a function", "create a program", "code example",
        "best programming language", "easiest language to learn"
    ],
    "science": [
        "do you know science", "tell me about science", "science facts",
        "explain science", "scientific knowledge", "are you scientific",
        "physics", "chemistry", "biology", "astronomy",
        "space facts", "universe", "planets", "stars",
        "atoms", "molecules", "elements", "periodic table",
        "gravity", "quantum physics", "relativity",
        "evolution", "dna", "cells", "organisms",
        "scientific method", "experiments", "research"
    ],
    "history": [
        "tell me history", "historical facts", "do you know history",
        "ancient history", "world history", "american history",
        "world war", "historical events", "past events",
        "famous people in history", "historical figures",
        "ancient civilizations", "rome", "egypt", "greece",
        "middle ages", "renaissance", "industrial revolution",
        "important dates", "timeline", "when did",
        "who discovered", "who invented", "origins of"
    ],
    "motivation": [
        "motivate me", "i need motivation", "inspire me",
        "give me motivation", "motivational quote", "inspire quote",
        "i feel lazy", "i lack motivation", "need inspiration",
        "encourage me", "i need encouragement", "cheer me up",
        "feeling unmotivated", "cant get started", "procrastinating",
        "boost my confidence", "i can do this", "pep talk",
        "words of encouragement", "inspirational words", "pump me up",
        "i need a push", "help me get motivated", "inspire to work"
    ],
    "advice": [
        "give me advice", "i need advice", "what should i do",
        "help me decide", "advise me", "your advice",
        "life advice", "good advice", "wise advice",
        "tips", "suggestions", "recommendations",
        "guidance", "counsel", "what do you suggest",
        "what would you do", "in your opinion what should",
        "best course of action", "wise choice", "smart move"
    ],
    "fitness": [
        "fitness tips", "how to get fit", "workout advice",
        "exercise routines", "gym tips", "working out",
        "how to lose weight", "weight loss", "diet tips",
        "healthy eating", "nutrition", "stay healthy",
        "build muscle", "get stronger", "cardio",
        "running tips", "yoga", "stretching",
        "fitness goals", "get in shape", "physical fitness",
        "health and fitness", "wellness", "active lifestyle"
    ],
    "travel": [
        "travel recommendations", "where should i travel",
        "best places to visit", "travel destinations",
        "vacation ideas", "holiday destinations",
        "travel tips", "traveling advice", "trip planning",
        "best countries", "beautiful places", "tourist spots",
        "adventure travel", "backpacking", "world travel",
        "cheap travel", "budget travel", "travel hacks",
        "solo travel", "family vacation", "romantic getaway"
    ],
    "technology": [
        "latest technology", "new tech", "technology trends",
        "future technology", "tech news", "innovations",
        "gadgets", "devices", "electronics",
        "smartphones", "computers", "laptops",
        "internet", "wifi", "networking",
        "cybersecurity", "privacy", "data security",
        "cloud computing", "blockchain", "cryptocurrency",
        "virtual reality", "augmented reality", "metaverse"
    ],
    "relationships": [
        "relationship advice", "dating tips", "love advice",
        "how to find love", "relationship help", "dating help",
        "friendship advice", "making friends", "social skills",
        "family issues", "relationship problems", "breakup advice",
        "healthy relationships", "toxic relationships",
        "communication tips", "trust issues", "jealousy",
        "long distance", "maintaining relationships",
        "conflict resolution", "forgiveness", "moving on"
    ],
    "career": [
        "career advice", "job search", "finding a job",
        "career tips", "job hunting", "employment",
        "interview tips", "resume help", "cv advice",
        "career change", "new career", "job switch",
        "promotion", "salary negotiation", "raise",
        "work life balance", "professional development",
        "skills to learn", "career growth", "advancement",
        "networking", "professional networking", "linkedin tips"
    ],
    "meditation": [
        "how to meditate", "meditation guide", "meditation tips",
        "teach me meditation", "mindfulness", "being mindful",
        "relaxation techniques", "stress relief", "calm down",
        "breathing exercises", "deep breathing", "relax",
        "inner peace", "mental clarity", "focus",
        "zen", "peaceful mind", "tranquility",
        "meditation benefits", "why meditate", "meditation practice"
    ],
    "dreams": [
        "dream interpretation", "what do dreams mean",
        "analyze my dream", "dream meanings", "dreaming",
        "nightmares", "bad dreams", "recurring dreams",
        "lucid dreaming", "control dreams", "dream symbols",
        "why do we dream", "dream analysis", "dream dictionary",
        "strange dreams", "vivid dreams", "prophetic dreams"
    ],
    "pets": [
        "do you like pets", "favorite pet", "pet advice",
        "dog or cat", "cats", "dogs", "animals",
        "pet care", "taking care of pets", "pet tips",
        "best pets", "good pets", "exotic pets",
        "pet training", "dog training", "cat behavior",
        "pet health", "veterinary", "pet food",
        "adopt a pet", "rescue animals", "pet adoption"
    ],
    "cooking": [
        "cooking tips", "how to cook", "recipe ideas",
        "easy recipes", "cooking advice", "chef tips",
        "baking", "how to bake", "baking tips",
        "healthy cooking", "meal prep", "cooking techniques",
        "kitchen tips", "culinary skills", "cooking skills",
        "learn to cook", "beginner cooking", "cooking basics",
        "favorite recipe", "what to cook", "dinner ideas"
    ],
    "philosophy": [
        "philosophy", "philosophical questions", "meaning of life",
        "purpose of life", "existential", "existence",
        "consciousness", "reality", "truth",
        "ethics", "morality", "right and wrong",
        "free will", "determinism", "fate",
        "mind and body", "soul", "afterlife",
        "famous philosophers", "philosophical thoughts",
        "deep questions", "think deeply", "ponder"
    ],
    "environment": [
        "climate change", "global warming", "environment",
        "environmental issues", "pollution", "sustainability",
        "eco friendly", "green living", "save the planet",
        "recycling", "renewable energy", "solar power",
        "conservation", "endangered species", "wildlife",
        "deforestation", "ocean pollution", "plastic waste",
        "carbon footprint", "reduce waste", "go green"
    ],
    "astronomy": [
        "space", "universe", "cosmos", "stars",
        "planets", "solar system", "galaxy",
        "black holes", "nebula", "astronomy",
        "constellations", "meteor", "asteroid",
        "mars", "moon", "sun", "earth",
        "telescope", "nasa", "space exploration",
        "aliens", "extraterrestrial", "life in space"
    ],
    "art": [
        "do you like art", "favorite art", "art styles",
        "painting", "drawing", "sculpture",
        "famous artists", "art history", "modern art",
        "abstract art", "impressionism", "renaissance art",
        "digital art", "graphic design", "illustration",
        "art techniques", "how to draw", "how to paint",
        "artistic", "creativity", "creative expression"
    ],
    "money": [
        "money advice", "financial tips", "save money",
        "saving tips", "budgeting", "budget help",
        "investing", "investment tips", "stocks",
        "make money", "earn money", "side hustle",
        "passive income", "financial freedom", "wealth",
        "debt", "pay off debt", "credit cards",
        "financial planning", "retirement", "savings account"
    ],
    "set_bot_name": [
        "your name is", "ill call you", "you are called", "you are named",
        "im naming you", "im calling you", "lets name you", "i name you",
        "your new name is", "from now on you are", "i want to call you",
        "id like to call you", "can i call you", "may i call you",
        "rename you", "give you a name", "pick a name for you",
        "ill name you", "naming you", "youll be called", "youll be named",
        "change your name to", "new name for you", "call yourself"
    ],
    "fashion": [
        "fashion tips", "style advice", "what to wear",
        "fashion trends", "latest fashion", "trendy",
        "outfit ideas", "clothing", "wardrobe",
        "fashion sense", "dress well", "look good",
        "accessories", "shoes", "jewelry",
        "fashion brands", "designer", "haute couture",
        "casual style", "formal wear", "streetwear"
    ]
}
